Repository anyproto/anytype-swift, pull requests merged in 2023-11, with the labels that each got.

#487 IOS-1933 Update middleware
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Labels: 🧠 no brainer

#488 IOS-1922 Spaces | Add gradient smoothing and fix layout
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/Common/Content/GradientIconPainter.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift
Labels: 🧠 no brainer

#490 IOS-1903 Spaces | Add spaceAccessibility
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/CoreLayer/StoreLayer/SpaceStorage/SpaceView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/Models/SpaceAccessibility+Localization.swift
  Modules/Services/Sources/Models/Space/SpaceAccessibility.swift
Labels: 🧠 no brainer

#507 IOS-1925 Add origin source when adding content from sharing extension
  Anytype/Sources/PresentationLayer/ShareView/ShareViewModelInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateBookmarkViewModel.swift
  Anytype/Sources/ServiceLayer/Dashboard/DashboardService.swift
  Anytype/Sources/ServiceLayer/Object/PageService/PageRepository.swift
  Modules/Services/Sources/Models/ObjectOrigin.swift
  Modules/Services/Sources/Services/Bookmark/BookmarkService.swift
  Modules/Services/Sources/Services/Bookmark/BookmarkServiceProtocol.swift
  Modules/Services/Sources/Services/PageService/PageService.swift
Labels: release

#510 iOS-1880 Spaces | Add deeplink to space selection menu
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinator.swift
  Anytype/Sources/CoreLayer/StoreLayer/AppActions/AppAction.swift
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
  Shared/SharedContants.swift
Labels: release

#511 iOS-1952 Object Icon | fix warning
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectIconPickerViewModel.swift
Labels: 🧠 no brainer, release

#512 iOS-1953 Object Type Provider | fix warning
  Anytype/Sources/CoreLayer/StoreLayer/SpaceStorage/ActiveWorkspaceStorage.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProvider.swift
Labels: 🧠 no brainer, release

#513 iOS-1900 Switch space | try to fix open document when space deleted on other device
  Anytype/Sources/CoreLayer/StoreLayer/SpaceStorage/ActiveWorkspaceStorage.swift
Labels: 🧠 no brainer, release

#514 iOS-1954 Errors | fix 404 log
  Anytype/Sources/CoreLayer/NetwrokLayer/AnytypeImageDownloader.swift
  Anytype/Sources/CoreLayer/NetwrokLayer/DownloadableImageViewWrapper/DownloadableImageViewWrapper.swift
Labels: 🧠 no brainer, release

#516 iOS-1944 Object Actions | Add text limit for different languages
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionRow.swift
Labels: 🧠 no brainer, release

#518 iOS-1947 Core & Spaces | Make some components as @MainActor for fix potential race condition
  Anytype/Sources/CoreLayer/StoreLayer/QuickActions/QuickActionBuilder.swift
  Anytype/Sources/CoreLayer/StoreLayer/SpaceStorage/ActiveWorkspaceStorage.swift
  Anytype/Sources/CoreLayer/StoreLayer/SpaceStorage/WorkspacesStorage.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Model/SearchViewModelProtocol.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/SearchModuleAssembly.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/SearchModuleAssemblyProtocol.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/BottomSheetsFactory.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextAttributesView/MarkupViewModel.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextAttributesView/MarkupViewModelProtocol.swift
  Anytype/Sources/PresentationLayer/LinkToObjectFlow/LinkToObjecttCoordinator.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/SpaceSearchViewModel/SpaceSearchViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/MarkupModeView/MarkupAccessoryViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableDependenciesBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/SetSubscriptionDataBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/SetSubscriptionDataBuilderProtocol.swift
  Anytype/Sources/ServiceLayer/Subscriptions/BinSubscriptionService.swift
  Anytype/Sources/ServiceLayer/Subscriptions/CollectionsSubscriptionService.swift
  Anytype/Sources/ServiceLayer/Subscriptions/FilesSubscriptionService.swift
  Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift
  Anytype/Sources/ServiceLayer/Subscriptions/SetsSubscriptionService.swift
Labels: release

#523 iOS-1965 Remove the template type from the types in Collection / Sets
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
  Modules/Services/Sources/Models/ObjectType.swift
Labels: release

#525 iOS-1963 Widgets | fix dismiss for legacy ios
  Anytype/Sources/PresentationLayer/Flows/CreateWidgetFlow/CreateWidgetCoordinatorViewModel.swift
Labels: 🧠 no brainer, release

#526 iOS-1970 Fix synced files subscriptions
  Anytype/Sources/ServiceLayer/Subscriptions/FilesSubscriptionService.swift
Labels: 🧠 no brainer, release

#527 iOS-1819 Set as default -> Make default
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: release

#528 iOS-1974 Fix - type from anytype library in the set is not applied
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
Labels: release

#529 iOS-1971 Disable type change for Templates
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Labels: release

#530 iOS-1973 Fix new template creation after deleting all in the picker
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsView.swift
Labels: release

#531 iOS-1972 Fix - deleting a template does not close the template
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingModuleAssembly.swift
Labels: release

#532 iOS-1968 Set template as default for type from template editing mode
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
Labels: release

#535 IOS-1681 Descrease minimum deployment version for Sharing Extension
  Anytype.xcodeproj/project.pbxproj
  AnytypeShareExtension/ShareViewController.swift
Labels: release

#538 iOS-1998 Search | Add profile from system space
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorAssembly.swift
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorBrowser/EditorBrowserCoordinator.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
  Anytype/Sources/ServiceLayer/Object/Search/Common/SearchHelper.swift
  Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
  Anytype/Sources/ServiceLayer/ServiceLocator.swift
  Modules/Services/Sources/Models/Account/AccountInfo.swift
Labels: release

#539 iOS-2003 Update middleware
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/changes.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Labels: release

#541 iOS-1870 Enable some localizations
  Anytype.xcodeproj/project.pbxproj
Labels: release

#540 iOS-1877 Change filter and change text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift
Labels: release

#546 iOs-2015 Update middleware
  Libraryfile
Labels: release

#552 IOS-2022 Increment patch
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
Labels: release

#550 IOS-1919 Widget List | Change section title
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Configurations/ListSectionConfiguration.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/List/ListSectionBigHeaderView.swift
  Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/WidgetObjectListView.swift
Labels: 🧠 no brainer

#564 Release -> main
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
  Libraryfile
Labels: release

#565 Ios 2043 relese develop
  Libraryfile
Labels: release

#579 IOS-2013 Editor | Create widget action | Fix filter
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectAction.swift
Labels: 🧠 no brainer

#581 iOS-1928 Fix editor placeholders color
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/Stylers/TextBlockTextViewStyler.swift
Labels: 🧠 no brainer

#582 iOS-2001 Fix Limit Object Types tab opening from Set/Collection
  Anytype/Sources/PresentationLayer/AddNewRelation flow/AddNewRelationCoordinator.swift
Labels: 🧠 no brainer
