Repository anyproto/anytype-swift, pull requests merged in 2023-12, with the labels that each got.

#583 IOS-2056 Char Icon | Uppercase
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/Common/Content/CharIconPainter.swift
Labels: 🧠 no brainer

#589 IOS-1894 Personalization | Fix background
  Anytype/Sources/PresentationLayer/Settings/Personalization/PersonalizationView.swift
Labels: 🧠 no brainer

#595 iOS-2055 Rename Link to object in Slash menu
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#598 IOS-2074 Editor | Fix cycle
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Labels: 🧠 no brainer

#599 IOS-2073 Delete state | Dismiss all modals (for legacy ios)
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorAssembly.swift
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
Labels: 🧠 no brainer

#619 iOS-1602 Self-hosted | Analytics
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics.swift
  Anytype/Sources/CoreLayer/StoreLayer/ServerConfigirationStorage/NetworkServerConfig.swift
  Anytype/Sources/PresentationLayer/Modules/ServerConfiguration/ServerConfigurationViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/ServerDocumentPicker/ServerDocumentPickerViewModel.swift
  Anytype/Sources/ServiceLayer/Auth/AuthService.swift
Labels: release

#623 IOS-2023 Sharing extension analytics & fixes
  Anytype/Resources/Assets.xcassets/SharingTip/step1.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/SharingTip/step1.imageset/step 1 2.png
  Anytype/Resources/Assets.xcassets/SharingTip/step1.imageset/step1.png
  Anytype/Resources/Assets.xcassets/SharingTip/step2.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/SharingTip/step2.imageset/step 2 2.png
  Anytype/Resources/Assets.xcassets/SharingTip/step2.imageset/step2.png
  Anytype/Resources/Assets.xcassets/SharingTip/step3.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/SharingTip/step3.imageset/step 3 1.png
  Anytype/Resources/Assets.xcassets/SharingTip/step3.imageset/step3.png
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/ShareView/ShareViewModelInteractor.swift
  Anytype/Sources/PresentationLayer/ShareView/SharingTip/SharingTipCoordinator.swift
  Anytype/Sources/PresentationLayer/ShareView/SharingTip/SharingTipView.swift
  Anytype/Sources/PresentationLayer/ShareView/SharingTip/SharingTipViewModel.swift
Labels: release

#622 iOS-2087 Make back button on bottom navigation always back
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: release

#620 iOS-2083 Any objects creation analytics fixes
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsFlow/HomeWidgetsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift
Labels: release

#618 iOS-1976 Remove manual type change filter from Template object
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
Labels: release

#621 iOS-2069 Synced status description is depending on networkId
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewInput.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorNavigationBarHelper/EditorNavigationBarHelper.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Navigation/EditorSyncStatusItem.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Navigation/SwiftUIEditorSyncStatusItem.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Navigation/SyncStatusData.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetMinimizedHeader.swift
Labels: release, WIP

#625 iOS-2089 Change link to description in slash menu
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
Labels: release

#627 iOS-2092 Integrate middle v0.30.0 rc5
  Libraryfile
Labels: release

#626 iOS-2093 Hide backlinks from featured relations if there is no values yet
  Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift
Labels: release

#632 iOS-2098 Tech | Enable remote logging for prod temp
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorAssembly.swift
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorView.swift
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
  Anytype/Sources/ApplicationLayer/Launch/LaunchView.swift
  Anytype/Sources/CoreLayer/MiddlewareHandler/MiddlewareHandlerConfigurator.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: release

#630 iOS-2095 Update widgets icon
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Dashboard.imageset/Dashboard.pdf
Labels: release

#637 iOS-2113 Subscribe on objectType updates in BaseDocument
  Anytype/Sources/Models/Documents/Document/BaseDocument.swift
  Anytype/Sources/ServiceLayer/DocumentsProvider/DocumentsProvider.swift
Labels: release

#642 iOS-2116 Integrate middle v0.30.0-rc6
  Libraryfile
Labels: release

#641 iOS-2098 Turn off remote logging for prod
  Anytype/Sources/CoreLayer/MiddlewareHandler/MiddlewareHandlerConfigurator.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: release

#640 iOS-2115 Fix template picker for iOS 16.4 and earlier
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerView.swift
Labels: release

#639 iOS-2099 Fix logout flow for iOS 16.4 and earlier
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
Labels: release

#645 iOS-2118 Integrate middle v0.30.0-rc7
  Libraryfile
Labels: release

#649 iOS-2087 Change common error text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/TextEditor/Views/Alerts/DocumentCommonOpenErrorView.swift
Labels: release

#651 iOS-2121 Integrate middle v0.30.0-rc8
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
  Libraryfile
Labels: release

#652 iOS-2099 Fix logout one more time
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardAlertsAssembly.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardLogoutAlert/DashboardLogoutAlertModel.swift
  Anytype/Sources/PresentationLayer/Settings/Coordinator/SettingsCoordinator.swift
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
Labels: release

#653 iOS-2126 Integrate middle v0.30.0
  Libraryfile
Labels: release

#654 iOS-2127 Block tracking users IP address property
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics.swift
Labels: release

#655 iOS-2131 Integrate middle v0.30.1
  Libraryfile
Labels: release

#658 iOS-2133 Integrate middle v0.30.2
  Libraryfile
Labels: release

#659 iOS-2134 Integrate middle v0.30.3
  Libraryfile
Labels: release
