Repository anyproto/anytype-swift, pull requests merged in 2023-08, with the labels that each got.

#233 IOS-1607 Editor | Fix analytics
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Labels: 🧠 no brainer

#246 iOS-1561 Fix logs - replace text with textLength
  Anytype/Sources/Models/Documents/Parsers/AttributedTextConverter.swift
Labels: 🧠 no brainer

#251 IOS-1608 Recent widget | Fix date filter
  Anytype/Sources/ServiceLayer/Subscriptions/RecentSubscriptionService.swift
  Modules/AnytypeCore/AnytypeCore/Utils/ArrayBuilder.swift
Labels: release

#252 iOS-1410 Fix prices error during release build
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
  Gemfile
  Gemfile.lock
  fastlane/FastfileDeploy
Labels: release

#253 IOS-1638 Update middle
  Libraryfile
Labels: release

#261 iOS-1639 integrate v0.27.18
  Libraryfile
Labels: 🧠 no brainer

#258 IOS-1589 Checkbox isn't showed in the template with layout Task
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
Labels: release

#265 IOS-1294 Core | Move BlockWidgetService
  Anytype.xcodeproj/project.pbxproj
  Modules/Services/Sources/Models/WidgetPosition.swift
  Modules/Services/Sources/Services/BlockWidget/BlockWidgetService.swift
Labels: 🧠 no brainer

#263 iOS-1649 Fix collection header availability
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
Labels: release

#268 iOS-1650 Add middletime property for CreateAccount event
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/ServiceLayer/Auth/AuthService.swift
Labels: release

#270 iOS-1658 Middleware | integrate v0.27.19
  Libraryfile
Labels: release

#269 IOS-1518 Templates. Design changes
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Assets.swift
  Anytype/Generated/Color+Assets.swift
  Anytype/Generated/Color+Info.swift
  Anytype/Generated/UIColor+Assets.swift
  Anytype/Resources/SystemColors.xcassets/Additional/editingBackground.colorset/Contents.json
  Anytype/Sources/Design system/Fonts/AnytypeFont.swift
  Anytype/Sources/Design system/Fonts/AnytypeFontConfig.swift
  Anytype/Sources/PresentationLayer/Templates/TemplateSelectionCoordinator.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/EditableView.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionView.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/VisualEffectView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelConfiguration.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Empty/ObjectHeaderEmptyContentView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader+Mutation.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeader.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderEmptyData.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Filled/Subviews/HeaderViewSizeConfiguration.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Filled/Subviews/Icon/ObjectHeaderIconView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Filled/Subviews/ObjectHeaderView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/ObjectHeaderConstants.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: Do not merge, release

#274 IOS-1662 Add template availability check in collections
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
  Anytype/Sources/ServiceLayer/Object/Templates/TemplatesInteractor.swift
  Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift
Labels: release

#278 IOS-1671 Update middleware to 0.27.20
  Libraryfile
  Modules/ProtobufMessages/Package.swift
Labels: release

#277 IOS-1676 Memory leak fix
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: release

#275 Ios 1517 sets new button additional option
  Anytype/Generated/Assets.swift
  Anytype/Generated/Color+Assets.swift
  Anytype/Generated/Color+Info.swift
  Anytype/Generated/ImageAssets.swift
  Anytype/Generated/Strings.swift
  Anytype/Generated/UIColor+Assets.swift
  Anytype/Resources/Assets.xcassets/ObjectSettings/Actions/template_make_default.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/ObjectSettings/Actions/template_make_default.imageset/Icon.pdf
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Resources/SystemColors.xcassets/Additional/separator.colorset/Contents.json
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButton.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/StandardButtonConfig.swift
  Anytype/Sources/PresentationLayer/Templates/Assembly/TemplateModulesAssembly.swift
  Anytype/Sources/PresentationLayer/Templates/TemplateSelectionCoordinator.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/MockTemplateSelectionInteractorProvider.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreviewModel.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionView.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectAction.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViews/ObjectActionsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
  Anytype/Sources/ServiceLayer/Object/Templates/TemplatesInteractor.swift
  Modules/Services/Sources/Services/Templates/TemplatesService.swift
Labels: release

#281 IOS-1518 Blank template options fix
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreview.swift
Labels: release

#282 Hotfix version
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
Labels: release

#283 iOS-1680 Update middleware
  Libraryfile
Labels: release

#297 IOS-1704 File Limits | Fix int range
  Anytype/Sources/CoreLayer/StoreLayer/FileLimitsStorage/FileLimitsStorage.swift
  Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
Labels: 🧠 no brainer

#302 IOS-1605 Delete flow | open deleted object in mentions and links
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
Labels: 🧠 no brainer

#305 IOS-1605 Delete flow | Update settings
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSetting.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
Labels: 🧠 no brainer
