Repository anyproto/anytype-swift, pull requests merged in 2023-09, with the labels that each got.

#329 IOS-1727 Update middle from the main (staging)
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/ServiceLayer/Auth/AuthServiceError.swift
  Anytype/Sources/ServiceLayer/Auth/CreateAccountServiceError.swift
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: release

#345 iOS-1740 IconView | fix problem with displaying checkboxes in the view grid
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/IconMaker.swift
Labels: release

#347 iOS-1743 Integrate middle v0.28.2
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/events.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Labels: release

#349 IOS-719 MiddlewareEventConverter | Move event handler methods
  Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
  Modules/Services/Sources/Models/Block/BlockContainer/InfoContainer+Events.swift
  Modules/Services/Sources/Models/Details/Storage/ObjectDetailsStorage+Events.swift
  Modules/Services/Sources/Models/Details/Storage/ObjectDetailsStorage.swift
  Modules/Services/Sources/Models/ObjectRestrictions/ObjectRestrictionsContainer+Events.swift
  Modules/Services/Sources/Models/Relations/Storage/RelationLinksStorageProtocol+Events.swift
Labels: tech

#350 iOS-1707 Support default type template if no activeview's template was selected
  Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreviewModel.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProvider.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProviderProtocol.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/Subscription/ObjectTypeSubscriptionDataBuilder.swift
  Modules/Services/Sources/Models/ObjectType.swift
Labels: release

#351 iOS-1756 Integrate middle v0.28.3
  Libraryfile
Labels: release

#352 iOS-1761 Integrate middle v0.28.4
  Libraryfile
Labels: release

#354 iOS-1762 Fix object type filter in Sets / Collections
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/Interactor/ObjectsSearchInteractor/ObjectsSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
Labels: release

#355 iOS-1763 Release to develop
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/IconView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/IconMaker.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/RelationViewProvider/RelationValueViewUIKit.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/ObjectsSearchViewModel/Interactor/ObjectsSearchInteractor/ObjectsSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Dataview/DataViewTemplateSelectionInteractorProvider.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/Objects/TemplatePreviewModel.swift
  Anytype/Sources/PresentationLayer/Templates/Views/Selection/TemplatesSelectionViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/ServiceLayer/Auth/AuthServiceError.swift
  Anytype/Sources/ServiceLayer/Auth/CreateAccountServiceError.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProvider.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/ObjectTypeProviderProtocol.swift
  Anytype/Sources/ServiceLayer/Object/ObjectType/Subscription/ObjectTypeSubscriptionDataBuilder.swift
  Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
  AnytypeWidget/AnytypeWidget.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/events.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
  Modules/Services/Sources/Models/ObjectType.swift
Labels: tech

#360 IOS-719 EventConverter | Move Dataview Events and some Info container events
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
  Anytype/Sources/Models/Extensions/DataviewType+Extensions.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Array+Dataview.swift
  Modules/Services/Sources/Models/Block/BlockContainer/InfoContainer+Events.swift
  Modules/Services/Sources/Models/Block/BlockContainer/InfoContainer+EventsDataview.swift
  Modules/Services/Sources/Models/Block/BlockContainer/InfoContainer+ModelHelpers.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockBookmark+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockDivider+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockFile+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockLink+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockRelation+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockWidget+Handle.swift
Labels: tech

#362 IOS-1605 Editor| Fix header style
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Navigation/EditorNavigationBarTitleView.swift
Labels: 🧠 no brainer

#364 iOS-1776 Increase patch version to 0.25.1
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
Labels: release

#365 iOS-1778 Integrate middle v0.28.5
  Libraryfile
Labels: release

#369 Tech | iOS-1763 Release to develop
  Libraryfile
Labels: tech

#370 Tech | Release to main
  Anytype.xcodeproj/project.pbxproj
  Anytype/Supporting files/Info.plist
  AnytypeTests/Info.plist
  Libraryfile
Labels: tech

#372 IOS-1577 Task | Add impact feedback
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Common/TreeWidgetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: 🧠 no brainer

#374 IOS-1784 Mention | Fix mention without icon
  Anytype/Sources/Models/Mention/MentionAttachment.swift
Labels: 🧠 no brainer

#368 IOS-1766 Get rid of header updates
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/CoreLayer/Navigation/NavigationContext.swift
  Anytype/Sources/Models/Documents/Document/BaseDocumentProtocol.swift
  Anytype/Sources/Models/Documents/Events/EventConverters/LocalEventConverter.swift
  Anytype/Sources/Models/Documents/Events/Model/DocumentUpdate.swift
  Anytype/Sources/Models/Documents/Events/Model/LocalEvent.swift
  Anytype/Sources/Models/Documents/Events/Model/UnsplashItem+LocalEvent.swift
  Anytype/Sources/PresentationLayer/Assemblies/ModulesDI.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/Settings/Coordinator/SettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/Settings/Coordinator/SettingsCoordinatorAssembly.swift
  Anytype/Sources/PresentationLayer/Templates/TemplateSelectionCoordinator.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorPageAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/TableOfContents/TableOfContentsContentProvider.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModelProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/ObjectHeaderViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Cover/ObjectCoverPickerModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Cover/ObjectCoverPickerViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Modules/ObjectIconPickerModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectIconPickerViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/ObjectProfileIconPicker.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
  Anytype/Sources/ServiceLayer/Block/File/NSItemProvider+Async.swift
  Anytype/Sources/ServiceLayer/Object/Details/DetailsService.swift
  Anytype/Sources/ServiceLayer/Object/Details/DetailsServiceProtocol.swift
  Anytype/Sources/ServiceLayer/ServiceLocator.swift
Labels: tech
