Repository anyproto/anytype-swift, pull requests merged in 2024-04, with the labels that each got.

#1082 IOS-2456 Rename | MembershipTierId -> MembershipTierType
  Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
  Modules/Services/Sources/Services/Membership/MembershipService.swift
  Modules/Services/Sources/Services/Membership/Model/MembershipTier.swift
Labels: 🧠 no brainer

#1112 IOS-2581 Editor | Fix relation animation
  Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Labels: 🧠 no brainer

#1120 iOS-2586 Basic | Fix warnings in EditorSetViewModel
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: 🧠 no brainer

#1136 IOS-2457 Space Manager | Fix export
  Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerViewModel.swift
  Anytype/Sources/PresentationLayer/Notifications/Specific/ParticipantRemove/ParticipantRemoveNotificationViewModel.swift
Labels: 🧠 no brainer

#1166 IOS-2600 Spaces Manager | Add local status filter
  Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerViewModel.swift
Labels: 🧠 no brainer

#1169 IOS-2613 Editor | Fix open object picker
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/AccessoryViewSwitcher.swift
Labels: 🧠 no brainer

#1172 IOS-2633 Spaces | Change text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#1182 IOS-2617 Set permission | fix empty state
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetView.swift
Labels: 🧠 no brainer

#1194 IOS-2395 Membership | Fix spelling
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/Design system/Colors/Gradients/MembershipTeirGradient.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierView/MembershipTierViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Labels: 🧠 no brainer

#1202 IOS-2427 Update settings order
  Anytype/Sources/PresentationLayer/Settings/Settings/SettingsView.swift
Labels: 🧠 no brainer

#1218 IOS-2345 Remote storage | Support only owned spaces
  Anytype/Sources/PresentationLayer/SpaceSettings/RemoteStorage/RemoteStorageViewModel.swift
Labels: 🧠 no brainer

#1228 IOS-2689 Change text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#1234 iOS-2696 Fix gallery layout in Set / Collection
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift
Labels: 🧠 no brainer

#1244 iOS-2599 Membership | payment preliminary bugs list fixes
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
Labels: 🧠 no brainer

#1254 iOS-2664 Another one text update
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#1259 IOS-2601 Space Join | Fix handle already join
  Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift
Labels: 🧠 no brainer

#1256 IOS-2620 Add proper price formatting
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierPaymentTypeExtension.swift
  Anytype/Supporting files/LocalStoreKitConfiguration.storekit
Labels: 🧠 no brainer

#1263 IOS-2713 Qr code | Change text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#1266 IOS-2714 Set | Fix permission
  Anytype/Sources/PresentationLayer/TextEditor/Set/Models/Builders/SetPermissionsBuilder.swift
Labels: 🧠 no brainer

#1268 IOS-2687 Space Share | Fix spacing
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/Subviews/InviteLinkView.swift
Labels: 🧠 no brainer

#1279 IOS-2717 Localization Template | fix widget target
  AnytypeWidget/Generated/Strings.swift
Labels: 🧠 no brainer

#1289 IOS-2729 Update middleware
  Libraryfile
Labels: 🧠 no brainer

#1288 IOS-2730 Enable toggle
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 no brainer

#1290 IOS-2732 Update crowdin
  crowdin.yml
Labels: 🧠 no brainer

#1253 iOS-2666 Onboarding | Update order of screens on black onboarding
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowCoordinator.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/Models/JoinFlowStep.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/VaultView/VaultView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/VaultView/VaultViewModel.swift
Labels: Do not merge

#1302 iOS-2742 Integrate middle v0.33.0-rc21
  Libraryfile
Labels: release

#1306 iOS-2666 Fix new onboarding text
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer

#1307 iOS-2741 Rename Default space to Entry space
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: release

#1309 iOS-2747 Integrate middle v0.33.0-rc22
  Anytype/Generated/Error+Localization.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: release

#1310 iOS-2439 Fix analytics
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Labels: release

#1312 iOS-2748 Set | disable change layout
  Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift
Labels: release

#1315 iOS-2070 Reduce cursor accessory view items for description
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/CursorModeView/CursorModeAccessoryViewModel.swift
Labels: release

#1320 IOS-2668 Use no cache option for membershipGetStatus
  Modules/Services/Sources/Services/Membership/MembershipService.swift
Labels: 🐞 bug

#1337 iOS-2772 Increase patch version to 0.29.1
  Anytype.xcodeproj/project.pbxproj
Labels: release

#1335 iOS-2770 Integrate middle v0.33.1
  Anytype/Generated/Error+Localization.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: release

#1336 iOS-2768 Fix task checked or unchecked on the object
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableCellsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockContentView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/Views/TextBlockIconVIew.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Header/Entities/HeaderBuilder.swift
Labels: release

#1360 iOS-2786 Attempt to fix crash call layout from the background thread
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
Labels: release
