Repository anyproto/anytype-swift, pull requests merged in 2024-07, with the labels that each got.

#1730 IOS-3056 Deep Links | Support external for Swiftui Scene
  Anytype/Sources/ApplicationLayer/AppSceneHandler/AppSceneUrlHandlerModifier.swift
Labels: 🧠 no brainer

#1763 IOS-3117 App | Fix handle invite qr code from camera app
  Anytype/Sources/ApplicationLayer/AppSceneHandler/AppSceneUrlHandlerModifier.swift
Labels: release

#1765 IOS-3123 Space Share | add missing update for delete link action
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Labels: release

#1767 iOS-3121 Object Settings | fix dismiss screen
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
Labels: release

#1768 iOS-3124 Base document | fix crash with subscriptions array
  Anytype/Sources/Models/Documents/Document/BaseDocument.swift
Labels: release

#1772 Ios-3128 Fix broken inline set in editor
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/DataView/DataViewBlockViewModel.swift
Labels: release

#1773 iOS-3129 Set widget | change list style
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift
Labels: release

#1776 IOS-3125 Update middleware
  Libraryfile
Labels: release

#1786 IOS-3142 Widgets | Change text
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetUnsupportedView.swift
Labels: 🧠 no brainer, release

#1787 iOS-3127 Fix exact date filter in Sets
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Date/SetFiltersDateRowView.swift
Labels: release

#1790 iOS-3146 Update middleware
  Libraryfile
  Modules/Services/Sources/Generated/BundledRelationKey+SystemKeys.swift
  Modules/Services/Sources/Generated/BundledRelationKey+internalKeys.swift
Labels: release

#1788 iOS-3102 Fix file extension conditions
  Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
  Modules/Services/Sources/Models/Details/FileDetails.swift
Labels: release

#1792 IOS-3153 Base Document | fix children
  Anytype/Sources/Models/Documents/Document/BaseDocument.swift
  Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
  Anytype/Sources/Models/Documents/Events/Model/DocumentUpdate.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/BaseDocumentProtocol+Home.swift
Labels: release

#1793 iOS-3154 Set Widget | Rollback list and compact list 😲
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRowModel+Details.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/Content/Subviews/ListWidgetRowModel+ObjectDetails.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/SetObject/SetObjectCompactListLegacyWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/SetObject/SetObjectCompactListWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/SetObject/SetObjectListLegacyWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Specific/SetObject/SetObjectListWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/SetObjecWidgetStyle.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/SetObjecWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/SetObjectViewRows.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/SetUnsupportedView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/Tabs/ViewWidgetTabsItemView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SetCommon/Tabs/ViewWidgetTabsView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/View/SetObjectViewWidgetSubmoduleView.swift
Labels: release

#1796 iOS-3150 Widget Source | Add new object button
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Labels: release

#1797 iOS-3157 Gallery widget | disable fit media
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRowModel+Details.swift
Labels: 🧠 no brainer, release

#1798 iOS-3151 Widget | texts update
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 no brainer, release

#1808 IOS-3078 Widget | Add analytics
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Submodules/HomeBottomPanel/HomeBottomPanelView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Internal/WidgetSourceSearchSelectInternalViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Labels: release

#1811 IOS-3179 Update middleware
  Libraryfile
Labels: 🧠 no brainer, release

#1812 IOS-3154 Set widget | Fix show unsupported view
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Labels: 🧠 no brainer, release

#1815 IOS-3154 Set widget | Fix show unsupported view
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Labels: 🧠 no brainer, release

#1834 IOS-3219 DesignSystem | update colors
  Anytype/Generated/Assets.swift
  Anytype/Generated/Color+Assets.swift
  Anytype/Generated/Color+Info.swift
  Anytype/Generated/UIColor+Assets.swift
  Anytype/Resources/SystemColors.xcassets/Background/highlightedLight.colorset/Contents.json
  Anytype/Resources/SystemColors.xcassets/Background/highlightedMedium.colorset/Contents.json
  Anytype/Sources/Design system/Buttons/ButtonsFactory.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchBar.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextStyleView/StyleCell/StyleCellConfiguration.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextStyleView/StyleView.swift
  Anytype/Sources/PresentationLayer/Modules/GallerySpaceSelection/GallerySpaceSelectionView.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/EditableView.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/TableView/RelationCellView/SlashMenuRealtionView.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/TableView/SlashMenuViewController+TableView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/BlocksOptionView/SelectionOptionsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/SetFilterRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Selection/Header/SetFiltersSelectionHeaderView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/List/SetSortRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/Views/UndoRedo/UndoRedoView.swift
Labels: 🧠 no brainer

#1839 IOS-2934 Core | Delete active workspace service in some places
  Anytype/Sources/PresentationLayer/Settings/About/AboutViewModel.swift
  Anytype/Sources/PresentationLayer/Settings/Coordinator/SettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Settings/Settings/SettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: 🧠 no brainer

#1842 iOS-3229 Release | update middleware
  Libraryfile
Labels: 🧠 no brainer, release

#1843 iOS-2934 Participant subscription | Add spaceId & redesign service
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Discussion/Subviews/Message/MessageViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Space/SpaceWidgetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpceMembers/SpaceMembersViewModel.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryData.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryViewModel.swift
  Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ActiveSpaceParticipantStorage.swift
  Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ParticipantsSubscription.swift
  Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ParticipantsSubscriptionProvider.swift
  Anytype/Sources/ServiceLayer/Auth/LoginStateService.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
  Anytype/Sources/ServiceLayer/SubscriptionsToggler/Internals/SubscriptionStorage.swift
Labels: tech

#1852 IOS-3239 Update middleware release
  Libraryfile
Labels: release

#1854 iOS-3237 Remove redundant @MainActor
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/VersionHistoryDataBuilder.swift
Labels: 🧠 no brainer
