Repository anyproto/anytype-swift, pull requests merged in 2024-10, with the labels that each got.

#2161 IOS-3508 ObjectLifecycleService | Ignore error
  Modules/Services/Sources/Services/ObjectLifecycleService/ObjectLifecycleService.swift
Labels: 🧠 no brainer

#2200 iOS-3538 Fix plural and widget localization
  Anytype.xcodeproj/project.pbxproj
Labels: release

#2203 iOS-3527 Popup for reindexing the spaces - fix clashing with tips
  Anytype/Sources/ApplicationLayer/AppConfigurators/AppConfigurator.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/AppVersionTrackerConfigurator.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/GlobalServicesConfiguration.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/TipsConfiguration.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/ServiceLayer/AppVersionTracker/AppVersionTracker.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
  Anytype/Sources/ServiceLayer/UserWarningAlertsHandler/UserWarningAlertsHandler.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: release

#2210 iOS-3550 Move create object popup in Sets / Collections to anytypesheet
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationData.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsView.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/SetObjectCreationSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsView.swift
Labels: release

#2212 iOS-3547 Fix Skip button and Key more info
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthBackgroundView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseMoreInfoView/KeyPhraseMoreInfoView.swift
Labels: release

#2220 IOS-3509 renamed page -> object
  Anytype/Sources/PresentationLayer/Common/UIKit/TextView/CustomTextView.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/TextView/CustomTextViewDelegate.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/TextView/Interactions/MentionAttributeSelectionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/SimpleTableCellsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/Block/TextBlock/SimpleTablesTextBlockActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockContentConfiguration.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockContentView+TextViewDelegate.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationCoordinator.swift
Labels: 🧠 no brainer

#2222 Ios-3556 participant subscriptions refining
  Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AccountParticipantsStorage.swift
  Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AcountParticipantSubscriptionBuilder.swift
  Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/ParticipantSpacesStorage.swift
  Modules/Services/Sources/Services/SearchService/SearchHelper.swift
Labels: release, PR to branch

#2230 iOS2828 Fix comment
  fastlane/FastfileDeploy
Labels: release

#2233 Ios-3565 Space hub | Fix deeplink race
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/HomePath.swift
Labels: release

#2242 Ios-3585 | Fixed constant account id use
  Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AccountParticipantsStorage.swift
  Anytype/Sources/ServiceLayer/AccountParticipantsStorage/AcountParticipantSubscriptionBuilder.swift
  Anytype/Sources/ServiceLayer/MultispaceSubscriptionHelper/MultispaceSubscriptionHelper.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/Subscription/ObjectTypeSubscriptionDataBuilder.swift
  Anytype/Sources/ServiceLayer/RelationStorage/Subscription/RelationSubscriptionDataBuilder.swift
  Anytype/Sources/ServiceLayer/Subscriptions/SingleObjectSubscriptionService.swift
Labels: 🐞 bug

#2243 iOS-3590 Core | Add middle domain for logs (to release branch)
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/NonFatalAlertConfigurator/NonFatalLoggerHandler.swift
  Anytype/Sources/CoreLayer/MiddlewareHandler/InvocationMesagesHandler.swift
  Modules/AnytypeCore/AnytypeCore/Logging/ErrorDomain.swift
  Modules/AnytypeCore/AnytypeCore/Utils/Asserts.swift
  Modules/ProtobufMessages/Sources/Invocation.swift
  Modules/ProtobufMessages/Sources/InvocationMesagesHandlerProtocol.swift
Labels: release

#2245 IOS-3588 Fix wrong color and name for new spaces
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Modules/Services/Sources/Services/Workspace/WorkspaceSetDetails.swift
Labels: 🐞 bug, release

#2246 iOS-3375 Remove redundant dateFormatter and fix typo
  Anytype/Sources/PresentationLayer/Common/SwiftUI/TipCustomViewPresentationModifier.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/TIps/SpaceHubTip/SpaceHubTipHandler.swift
  Anytype/Sources/PresentationLayer/Modules/ShareOptions/SharingTip/SharingTipHandler.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSectionBuilder.swift
Labels: 🧠 no brainer

#2247 iOS-3594 Fix object search spaceId error
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
Labels: release

#2253 IOS-3603 Limit number of private spaces to 50
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchViewModel.swift
  Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/WorkspacesStorage.swift
Labels: release

#2255 IOS-3607 Update middleware
  Libraryfile
Labels: release

#2258 IOS-3600 Remove list layouts from default object picker
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
Labels: release

#2263 IOS-3613 Hide plus in navbar if we exceeded number of private spaces
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Labels: 🐞 bug, release

#2269 iOS-3614 fix localization
  Anytype/Generated/Strings.swift
  AnytypeWidget/Generated/Strings.swift
  Tools/SwiftGen/SwiftGen_SwiftGenCLI.bundle/Contents/Resources/templates/strings/structured-swift5.stencil
Labels: release

#2301 IOS-3633 Setup spacehub only once
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Labels: release

#2314 iOS-3373 Date as an object | Add toggle to screen type
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
Labels: 🧠 no brainer

#2315 IOS-3660 CI | Remove timeouts
  .github/workflows/branch_build.yaml
  .github/workflows/dev_build.yaml
  .github/workflows/pr_tests.yml
  .github/workflows/release_build.yaml
  .github/workflows/test_fastlane_build.yaml
Labels: 🧠 no brainer
