Repository anyproto/anytype-swift, pull requests merged in 2024-03, with the labels that each got.

#906 IOS-2402 Update middle
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/Services/Sources/Generated/BundledRelationKey+SystemKeys.swift
  Modules/Services/Sources/Generated/BundledRelationKey.swift
  Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
Labels: release

#919 iOS-2408 Update middleware
  Libraryfile
Labels: 🧠 no brainer, release

#925 iOS-2108 Fix tags max count
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Relations/RelationViewProvider/ValueViews/Views/Tag/TagRelationView.swift
Labels: 🧠 no brainer

#927 iOS-2032 Update middleware & increment build
  Anytype.xcodeproj/project.pbxproj
  Libraryfile
Labels: release

#937 iOS-1805 Gallery | Design fixes
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Painters/Common/Container/SquareIconPainter.swift
  Anytype/Sources/PresentationLayer/Modules/GalleryInstallationPreview/Subviews/GalleryInstallationPreviewManifestView.swift
  Anytype/Sources/PresentationLayer/Modules/GallerySpaceSelection/GallerySpaceSelectionView.swift
Labels: release

#938 iOS-2428 update middleware
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: release

#947 IOS-2436 Fix show profile layout
  Modules/Services/Sources/Models/Extensions/DetailsLayout+Visible.swift
Labels: release

#949 IOS-2341 Search | Allow canCreateObjectOfThisType restriction
  Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
  Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/SetObjectCreationSettingsCoordinator.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Selection/Dataview/SetObjectCreationSettingsInteractor.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/Assembly/ObjectTypeSearchModuleAssembly.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Interactor/Legacy_ObjectTypeSearchInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/EditorAccessoryView/ChangeTypeAccessoryView/ChangeTypeAccessoryViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetRouter.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/Subscription/ObjectTypeSubscriptionDataBuilder.swift
  Anytype/Sources/ServiceLayer/Object/TypesService/TypesPinStorage.swift
  Anytype/Sources/ServiceLayer/Object/TypesService/TypesService.swift
  Anytype/Sources/ServiceLayer/Object/TypesService/TypesServiceProtocol.swift
  Modules/Services/Sources/Models/ObjectRestrictions/ObjectRestrictions.swift
  Modules/Services/Sources/Models/ObjectType.swift
  Modules/Services/Sources/Services/SearchService/SearchHelper.swift
Labels: release

#962 iOS-2436 Set | add hidden filter
  Anytype/Sources/PresentationLayer/TextEditor/Set/Subscriptions/Set/SetSubscriptionData.swift
Labels: release

#995 IOS-2487 Spaces | Rename Personal to Default space
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/CreatingSoulView/CreatingSoulView.swift
Labels: 🧠 no brainer

#1003 IOS-2487 Spaces | Change access type for create space
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
Labels: 🧠 no brainer

#1005 iOS-2495 Sharing Extension | fix analytics
  Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
  Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsModuleAssembly.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProviderProtocol.swift
  Modules/Services/Sources/Models/Details/FileDetails.swift
Labels: release

#1068 IOS-2456 Rename
  Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinator.swift
  Anytype/Sources/PresentationLayer/Flows/MembersipCoordinator/MembershipCoordinatorModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/NameSheet/MembershipNameSheetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipTierInfoView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Views/MembershipTierSuccessView.swift
  Modules/Services/Sources/Services/Membership/MembershipService.swift
  Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift
Labels: 🧠 no brainer

#1074 IOS-2456 Rename | userMembership.tier -> userMembership.tierId
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTeirView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/Views/MembershipTierListView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/MembershipTierSelectionView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/Views/MembershipOwnerInfoSheetView.swift
  Anytype/Sources/PresentationLayer/Settings/Settings/SettingsView.swift
  Modules/Services/Sources/Services/Membership/MembershipService.swift
  Modules/Services/Sources/Services/Membership/Model/MembershipStatus.swift
Labels: 🧠 no brainer
