Repository anyproto/anytype-swift, pull requests merged in 2024-12, with the labels that each got.

#2461 IOS-3795 Fixed lost asset
  Anytype/Resources/Assets.xcassets/DesignSystem/ObjectSettings/Layout.imageset/Contents.json
Labels: 🧠 No brainer

#2466 IOS-3757 Updated copy for created banners
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#2474 IOS-3814 Chat | Enable for specific space id
  Anytype/Sources/PresentationLayer/Modules/Chat/Models/FeatureFlags+Helper.swift
  Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
Labels: 🧠 No brainer

#2479 iOS-3138 Change releaseVersion for primitives
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 No brainer

#2481 IOS-3785 Fix typos
  Anytype/Sources/PresentationLayer/Modules/SpaceSwitch/SpaceSwitchViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpacesManager/Subviews/SpacesManagerRowView.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
  Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/Model/ParticipantSpaceViewData.swift
  Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/Model/SpacePermissions.swift
Labels: 🧠 No brainer

#2483 IOS-3461 Core | Enable SWIFT_UPCOMING_FEATURE_DEPRECATE_APPLICATION_MAIN
  Anytype.xcodeproj/project.pbxproj
Labels: 🧠 No brainer

#2484 iOS-3464 Core | Enable SWIFT_UPCOMING_FEATURE_IMPLICIT_OPEN_EXISTENTIALS
  Anytype.xcodeproj/project.pbxproj
Labels: 🧠 No brainer

#2486 iOS-3817 Integrate middle v0.38.1
  Anytype/Generated/Error+Localization.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
  Modules/Services/Sources/Generated/BundledRelationKey.swift
  Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
Labels: Release

#2487 iOS-3467 Core | Enable SWIFT_UPCOMING_FEATURE_ISOLATED_DEFAULT_VALUES
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/CoreLayer/Helpers/TimingTimer.swift
  Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/FrameCatcher.swift
  Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/PositionCatcher.swift
  Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/View+ReadSafeArea.swift
  Anytype/Sources/FrameworkExtensions/SwiftUI/Geometry/View+ReadSize.swift
  Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
  Anytype/Sources/PresentationLayer/Common/Factories/AlertModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/OffsetAwareScrollView.swift
  Anytype/Sources/ServiceLayer/ServerConfigirationStorage/ServerConfigirationStorage.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
Labels: 🧠 No brainer

#2489 IOS-3467 Core | Enable SWIFT_UPCOMING_FEATURE_INFER_SENDABLE_FROM_CAPTURES & Move settings from target to project
  Anytype.xcodeproj/project.pbxproj
Labels: 🧠 No brainer

#2488 IOS-3636 Fix typo
  Anytype/Sources/ServiceLayer/MultispaceSubscriptionHelper/MultispaceOneActiveSubscriptionHelper.swift
Labels: 🧠 No brainer

#2500 iOS-3835 Integrate middle v0.38.2
  Libraryfile
Labels: Release

#2504 iOS-3827 Date as an object | Update mentions texts if needed
  Anytype/Sources/Models/Documents/Events/DocumentViewModelSetter.swift
  Anytype/Sources/Models/Documents/Events/MentionMarkupEventProvider.swift
  Anytype/Sources/Models/Documents/MentionTextUpdateHandler/MentionTextUpdateHandler.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
  Anytype/Sources/ServiceLayer/Subscriptions/Tree/TreeSubscriptionDataBuilder.swift
Labels: Release

#2507 iOS-3837 Date as an object | Add relative tag
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Labels: Release

#2506 iOS-3840 Fix space icon issue
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Icon.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsModuleOutput.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerViewModel.swift
  Modules/Services/Sources/Models/Details/ObjectIcon.swift
Labels: Release

#2510 IOS-3825 Enabled relation editing for files or media
  Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
Labels: Release

#2512 iOS-3837 Date as an object | Add relative tag
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Labels: Release

#2509 IOS-3735 Updated order of object actions
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingBuilder.swift
Labels: 🧠 No brainer

#2513 iOS-3833 Chat | fix toggle & update header design
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Chat.imageset/Chat.pdf
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Widgets.imageset/Widgets.pdf
  Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeTabBar/HomeTabBarCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeTabBar/Subviews/HomeTabBarView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Labels: Release

#2514 IOS-3845 Auth | fix phrase colors after update colors asset
  Anytype/Sources/PresentationLayer/Auth/PhraseTextView/UIPhraseTextView.swift
Labels: Release

#2516 iOS-3833 Chat | fix show space widget
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
Labels: Release

#2518 iOS-3853 Integrate v0.38.3
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: Release

#2532 iOS-3862 Rename `Mentioned in` to `Mentions`
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Labels: Release

#2536 IOS-3450 Remove block file from file layout
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Modules/Services/Sources/Models/Block/BlockInformation/BlockInfromationExtension.swift
Labels: Release

#2538 iOS-3867 Integrate v0.38.5
  Libraryfile
Labels: Release

#2539 iOS-3868 Integrate middle v0.38.6
  Libraryfile
Labels: Release

#2544 iOS-3869 Fix profile icon
  Anytype/Sources/PresentationLayer/Settings/Settings/SettingsViewModel.swift
Labels: Release

#2545 iOS-3870 Remove create type button for viewers on object type screen
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
Labels: Release

#2546 iOS-3871 Date as an object | Filter creation date by origin
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/Subscription/DateRelatedObjectsSubscriptionService.swift
Labels: Release

#2537 IOS-3821 Primitives | Drastically reduced complexity of relations screen and removed hacks
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsData.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRelationsDataBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRowBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: PR to branch

#2549 iOS-3876 Fix participants subscription filters
  Anytype/Sources/ServiceLayer/ActiveSpaceParticipantsStorage/ParticipantsSubscription.swift
Labels: Release

#2555 Ios-3821 Primitives | Relations reorder dnd
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerAdditionalTests.swift
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveBetweenSectionTests.swift
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveWithinSectionTests.swift
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/MoveIndicator.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsDropDelegate.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
  AnytypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerGeneralTests.swift
  AnytypeTests/Markdown/Mocks/MockBaseDocument.swift
  AnytypeTests/Markdown/Mocks/MockRelationsService.swift
  AnytypeTests/Markdown/Mocks/Models+Mocks.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/Services/Sources/Services/Relations/RelationsService.swift
  Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift
Labels: PR to branch
