Repository anyproto/anytype-swift, pull requests merged in 2024-05, with the labels that each got.

#1383 IOS-2814 Cleanup service locator from unused methods
  Anytype/Sources/PresentationLayer/Flows/TypeSearchForNewObjectFlow/TypeSearchForNewObjectCoordinatorAssembly.swift
  Anytype/Sources/PresentationLayer/Flows/TypeSearchForNewObjectFlow/TypeSearchForNewObjectCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableDependenciesBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
  Anytype/Sources/ServiceLayer/ServiceLocator.swift
Labels: 🧠 no brainer

#1385 IOS-2814 Cleanup service locator form unused methods
  AnyTypeTests/Text/KeyboardActionHandlerTests.swift
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDI.swift
  Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorAssembly.swift
  Anytype/Sources/PresentationLayer/Flows/HomeFlow/HomeCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableDependenciesBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationCoordinator.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Creation/SetObjectCreationCoordinatorAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/KeyboardActionHandler/KeyboardActionHandler.swift
  Anytype/Sources/ServiceLayer/ServiceLocator.swift
Labels: 🧠 no brainer

#1400 IOS-2797 Fix typo
  Modules/Services/Sources/Services/Membership/MembershipModelBuilder.swift
  Modules/Services/Sources/Services/Membership/MembershipService.swift
Labels: 🧠 no brainer

#1421 IOS-2563 Spaces manager | Fix joining sort & fix icon
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView.swift
  Anytype/Sources/PresentationLayer/Modules/SpacesManager/SpacesManagerViewModel.swift
Labels: 🧠 no brainer

#1422 IOS-2709 Spaces | delete shared space
  Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/SpacePermissions.swift
Labels: 🧠 no brainer

#1423 IOS-2764 Space Join | support deleted space
  Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift
Labels: 🧠 no brainer

#1431 IOS-2395 Membership | Add icon for custom tier
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/Membership/tier_custom_medium.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/Membership/tier_custom_medium.imageset/tier_custom_medium.pdf
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
Labels: 🧠 no brainer

#1443 IOS-2776 Link to | Fix icon color
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Link to.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Link to.imageset/Link to.pdf
  Anytype/Resources/Assets.xcassets/ObjectSettings/Actions/link_to_itself.imageset/link_to_itself.pdf
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionRow.swift
Labels: 🧠 no brainer

#1445 IOS-2563 Space share | Fix participant sort
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareViewModel.swift
Labels: 🧠 no brainer

#1449 IOS-2825 Widget | Fix height for one object
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/List/Common/ListWidgetView.swift
Labels: 🧠 no brainer

#1450 IOS-2865 Space Join | Add network id for request
  Anytype/Sources/PresentationLayer/Modules/SpaceJoin/SpaceJoinViewModel.swift
  Modules/Services/Sources/Services/Workspace/WorkspaceService.swift
Labels: 🧠 no brainer

#1454 iOS-2867 Fix duplicate HomeCoordinatorViewModel warning
  Anytype.xcodeproj/project.pbxproj
Labels: 🧠 no brainer

#1428 IOS-2343 Editor | File blocks | migrate to targetObjectId
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/Analytics/Converters/BlockContentType+Analytics.swift
  Anytype/Sources/CoreLayer/NetwrokLayer/DownloadableContent/DownloadableContentProtocol.swift
  Anytype/Sources/FrameworkExtensions/Combine/CombineExtension.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/ImageViewer/ImageViewer/BlockFile+Paths.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/ImageViewer/ImageViewer/PreviewItem/FilePreviewMedia.swift
  Anytype/Sources/PresentationLayer/Common/UIKit/ImageViewer/ImageViewer/PreviewItem/ImageSourceMedia.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/Helpers/Document+WidgetTargetSubscriptions.swift
  Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockContentConfiguration.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockContentView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockPlayerDelegate.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/BlockFileView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/BlockFileViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/Utils/BlockFile+MediaData.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Image/BlockImageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Modules/Services/Sources/Models/Block/BlockContainer/Models+Events/BlockFile+Handle.swift
  Modules/Services/Sources/Models/Block/BlockContent/BlockContent.swift
  Modules/Services/Sources/Models/Block/BlockContent/Content/BlockFile.swift
  Modules/Services/Sources/Models/Block/BlockConverters/BlockFileConverter.swift
  Modules/Services/Sources/Models/Block/BlockInformation/BlockInformation+Creation.swift
  Modules/Services/Sources/Models/Block/Common/FileContentType.swift
  Modules/Services/Sources/Models/Details/FileDetails.swift
Labels: Do not merge

#1493 iOS-2900 Hotfix
  Anytype.xcodeproj/project.pbxproj
  Libraryfile
Labels: release

#1495 iOS-2852 Search | Update middle, disable autocapitalization for searchbar
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/SearchView/SearchBar.swift
  Libraryfile
Labels: 🧠 no brainer

#1506 iOS-2911 Integrate v0.33.6
  Anytype.xcodeproj/project.pbxproj
  Libraryfile
Labels: release

#1507 IOS-2785 Editor | Fix checkbox
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/Stylers/TextBlockLeadingView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockContentView.swift
Labels: 🧠 no brainer

#1516 iOS-2915 Remove textfield focus delay
  Anytype/Sources/PresentationLayer/Common/SwiftUI/iOS15Wrappers/AutofocusedTextField.swift
Labels: 🧠 no brainer

#1527 iOS-2899 Search | Add event to Search by Input
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/AnalyticsConfigurator.swift
  Anytype/Sources/PresentationLayer/Auth/DeletedAccount/DeletedAccountViewModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardAccountDeletionAlert/DashboardAccountDeletionAlertModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardLogoutAlert/DashboardLogoutAlertModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerViewModel.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
  Anytype/Sources/ServiceLayer/ObjectHeaderUploadingService/ObjectHeaderUploadingService.swift
Labels: 🧠 no brainer

#1525 iOS-2912 Search | Add event to Search by Backlink
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/AnalyticsConfigurator.swift
  Anytype/Sources/PresentationLayer/Auth/DeletedAccount/DeletedAccountViewModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardAccountDeletionAlert/DashboardAccountDeletionAlertModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Views/Alerts/DashboardLogoutAlert/DashboardLogoutAlertModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Models/BlockViewModelBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Space/SpaceObjectIconPickerViewModel.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionService/BlockActionService.swift
  Anytype/Sources/ServiceLayer/ObjectHeaderUploadingService/ObjectHeaderUploadingService.swift
Labels: 🧠 no brainer

#1529 IOS-2914 Editor | Style menu | Fix spacing
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextAttributesView/MarkupViewController.swift
Labels: 🧠 no brainer

#1543 iOS-2899 Search | Send SearchInput only if searchText is not empty
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
Labels: 🧠 no brainer
