Repository anyproto/anytype-swift, pull requests merged in 2024-11, with the labels that each got.

#2329 iOS-3666 Patch release | Go to the widgets by long tap on back button
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/ReturnToWidgetsTip.swift
Labels: Release

#2331 iOS-3667 Add dynamic Bin widget to home screen
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: Release

#2333 IOS-3682 Fix subscriptions task
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
Labels: Release

#2334 iOS-3683 Rename metricsSetParameters to setInitialParameters
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/MiddlewareMerticsConfigurator.swift
  Modules/Services/Sources/Services/Metrics/MetricsService.swift
Labels: 🧠 No brainer

#2262 fix: keyboard covers emoji search results
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Common/Emoji/EmojiGridView.swift
Labels: Waiting for branch tests

#2275 fix: blocks moved to another object are out of order
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageBlocksStateManager.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandler.swift
  Anytype/Sources/ServiceLayer/Block/BlockActionHandler/BlockActionHandlerProtocol.swift
  Modules/Services/Sources/Services/BlockService/BlockService.swift
  Modules/Services/Sources/Services/BlockService/BlockServiceProtocol.swift
Labels: Waiting for branch tests

#2357 IOS-3712 Add template spaceid key
  Modules/Services/Sources/Models/SubscriptionData/BundledRelationKey+CommonKeys.swift
Labels: Release

#2344 iOS-3695 Patch 0.33.5 | Support new progress bar protocol (without design)
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Error+Localization.swift
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/MiddlewareMerticsConfigurator.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/changes.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/events.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
  Modules/Services/Sources/Generated/BundledRelationKey+SystemKeys.swift
  Modules/Services/Sources/Generated/BundledRelationKey.swift
  Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
  Modules/Services/Sources/Generated/ObjectTypeUniqueKey+Bundled.swift
  Modules/Services/Sources/Services/Metrics/MetricsService.swift
  Modules/Services/Sources/Services/Process/Process.swift
Labels: Release

#2287 feat: support iPadOS Split View and Slide Over
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageController.swift
  Anytype/Supporting files/Info.plist
Labels: Waiting for branch tests

#2380 IOS-3636 Renamed EditorViewType set -> list
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x18/List.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x18/List.imageset/set or coolection.pdf
  Anytype/Sources/Models/Extensions/ObjectDetailsExtensions.swift
  Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Tree/Common/TreeWidgetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/DataView/DataViewBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/EditorPageViewModel+ChangeType.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/History/Object/ObjectVersionViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: 🧠 No brainer

#2388 iOS-3667 Return Bin widget
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: Release

#2386 iOS-3732 Date as an object | Special design for mention relation
  Anytype/Generated/ImageAssets.swift
  Anytype/Generated/Strings.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Mention.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Mention.imageset/Mention.pdf
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/RelationItemData.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSearchListView/SimpleSearchListView.swift
Labels: PR to branch

#2390 iOS-3737 Date as an object | Add date changing inside Date object
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Calendar.imageset/Calendar.pdf
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Calendar.imageset/Contents.json
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateModuleOutput.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Labels: PR to branch

#2397 IOS-3738 Home | fix set widget
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
Labels: 🧠 No brainer

#2402 iOS-3737 Date as an object | Add prev / next days arrows
  AnyTypeTests/Formatters/RelativeDateFormatterTests.swift
  Anytype.xcodeproj/project.pbxproj
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/FrameworkExtensions/Foundation/DateExtension.swift
  Anytype/Sources/Helpers/Formatters/DateFormatter+Relation.swift
  Anytype/Sources/Models/Relations/RelationsBuilder.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipStatusExtension.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/Mention/MentionViewController/MentionsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/RelationFilterBuilder.swift
Labels: PR to branch

#2407 iOS-3740 Date as an object | Add custom sorting
  Anytype/Sources/PresentationLayer/Modules/Date/DateModuleState.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/Subscription/DateRelatedObjectsSubscriptionService.swift
  Modules/Services/Sources/Services/SearchService/SearchHelper.swift
Labels: PR to branch

#2408 iOS-3745 Date as an object | Filter relations
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
Labels: PR to branch

#2418 iOS-3759 Date as an object | Add apply button to Calendar view
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/CoreLayer/Navigation/NavigationContext.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/CalendarView/CalendarConfirmationDateView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/CalendarView/CalendarView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/DateCalendarView/DateCalendarData.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/DateRelationCalendarView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/RelationOptionSettings/RelationOptionSettingsConfiguration.swift
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/View/LegacySearchView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Kanban/Column/Settings/SetKanbanColumnSettingsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Checkbox/SetFiltersCheckboxView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Date/SetFiltersDateView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Selection/List/SetFiltersSelectionView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/Text/SetFiltersTextView.swift
Labels: PR to branch

#2425 iOS-3750 Fix typo
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#2428 iOS-3768 Date as an object | Limit widget type to link for Date objects
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
Labels: PR to branch

#2433 iOS-3670 Date as an object | Design review
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/View+DragIndicator.swift
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/DateCoordinator/DateCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/RelationValueFlow/RelationValueCoordinator/RelationValueProcessingService.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift
Labels: PR to branch

#2440 IOS-3794 Chat | Disable keyboard handling if modal screen opened
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Collection/ChatCollectionViewContainer.swift
Labels: 🧠 No brainer

#2444 iOS-3766 Date as an object | Add `/date` command
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionObject.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Labels: PR to branch

#2443 iOS-3670 Date as an object | Add To Bin action for objects
  Anytype/Sources/PresentationLayer/Modules/Date/DateView.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/ObjectCellData.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Builders/SlashMenuItemsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/Actions/SlashActionObject.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockActionHandler.swift
Labels: PR to branch
