Repository anyproto/anytype-swift, pull requests merged in 2025-09, with the labels that each got.

#3878 IOS-4889 Updated cam icon
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Camera.imageset/Camera.svg
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Camera.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Camera.imageset/Image from Camera.svg
Labels: 🧠 No brainer

#3929 IOS-5156 Object Type widget | fix edit button and enable toggle
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 No brainer

#3930 IOS-5158 Sharing Extension | fix chat logic
  Anytype/Sources/PresentationLayer/Modules/SharingExtensionShareTo/SharingExtensionShareToViewModel.swift
Labels: 🧠 No brainer

#3978 IOS-5213 Chat Widget | show plus for create object
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/ObjectType/ObjectTypeWidgetView.swift
Labels: Release

#3979 IOS-5214 Widgets | fix pin if home is empty
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
Labels: Release

#3966 iOS-5195 Core | enable swift 6 & bump xcode to 26 (merge after freeze)
  .github/workflows/license-checks.yml
  .github/workflows/pr_tests.yml
  .github/workflows/release_build.yaml
  .github/workflows/test_fastlane_build.yaml
  .github/workflows/update_cache.yaml
  .github/workflows/update_middleware.yaml
  AnyTypeTests/Helpers/SendableTypes.swift
  AnyTypeTests/Markdown/Mocks/MockPropertiesService.swift
  AnyTypeTests/Markdown/Mocks/MockPropertyDetailsStorage.swift
  AnyTypeTests/Text/KeyboardActionHandlerTests.swift
  Anytype.xcodeproj/project.pbxproj
  Anytype.xcodeproj/xcshareddata/xcschemes/Anytype.xcscheme
  Anytype.xcodeproj/xcshareddata/xcschemes/AnytypeShareExtension.xcscheme
  Anytype.xcodeproj/xcshareddata/xcschemes/AnytypeWidgetExtension.xcscheme
  Anytype/Sources/Models/Mention/MentionAttachment.swift
  Anytype/Sources/PresentationLayer/Assemblies/CoordinatorsDI.swift
  Anytype/Sources/PresentationLayer/Debug/Flows/InternalDebug/DebugMenuViewModel.swift
  Anytype/Sources/PresentationLayer/Settings/Appearance/AppIcon/AppIconManager.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Base/BlockViewModelProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Bookmark/BlockBookmarkViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/DataView/DataViewBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Embed/EmbedBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/FeaturedRelations/FeaturedPropertiesBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/BlockFileViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Image/BlockImageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Video/VideoBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Property/PropertyBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/SimpleTable/SimpleTableBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Text/Base/TextBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Common/LinkToSearchHandling.swift
  Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
  Anytype/Sources/ServiceLayer/MultispaceSubscriptionHelper/MultispaceOneActiveSubscriptionHelper.swift
  Anytype/Sources/ServiceLayer/MultispaceSubscriptionHelper/MultispaceSubscriptionHelper.swift
  AnytypeTests/Markdown/Mocks/BlockListServiceMock.swift
  AnytypeTests/Markdown/Mocks/InfoContainerMock.swift
  AnytypeTests/Markdown/Mocks/MockBaseDocument.swift
  Modules/AsyncTools/Sources/AsyncTools/AsyncThrottle.swift
  Modules/AsyncTools/Sources/AsyncTools/AsyncToPublisher.swift
  Modules/NotificationsCore/Sources/NotificationsCore/Center/NotificationsCenterService.swift
Labels: Do not merge

#3989 iOS-5220 Widgets | fix id
  Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift
Labels: Release

#3990 iOS-5216 Widgets | fix create object for viewer
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
Labels: Release

#3999 IOS-5231 Fix SF symbols for older versions of iOS
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
Labels: Release

#4000 iOS-5224 AnytypeCircleCheckbox | change default style
  Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinSelectionView/InfoSelectionView/InfoSelectionView.swift
  Anytype/Sources/PresentationLayer/Modules/SharingExtension/Subviews/SharingExtensionSpaceView.swift
  Modules/DesignKit/Sources/DesignKit/Components/Checkbox/AnytypeCircleCheckbox.swift
Labels: Release

#4003 iOS-5235 Queries | add types for filters and queries
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/ObjectTypesLimitedSearchView.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/Interactor/Legacy_ObjectTypeSearchInteractor.swift
Labels: Release

#4006 IOS-5239 Do not show members management controls if used does not have permissions
  Anytype/Sources/PresentationLayer/Modules/NewSpaceShare/NewSpaceShareViewModel.swift
Labels: Release

#4005 IOS-5234 Support viewer permissions for types
  Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ObjectType/ObjectTypeTemplatePickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/ObjectType/ObjectTypeTemplatePickerViewModel.swift
Labels: Release
