Repository anyproto/anytype-swift, pull requests merged in 2025-04, with the labels that each got.

#3042 IOS-4360 Design review | Fix disclosure indicator
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Buttons/RoundedButtonView.swift
Labels: 🧠 No brainer

#3044 Ios-4378 Primitives | type description is deleted
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/Legacy_ObjectTypeSearchViewModel/MultiselectObjectTypesSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/Subscription/ObjectTypeSubscriptionDataBuilder.swift
Labels: 🧠 No brainer

#3047 IOS-4373 Primitives | Updated wordings
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/NewTypeCreation/ObjectTypeInfoView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Modules/Loc/Sources/Loc/Generated/Strings.swift
  Modules/Loc/Sources/Loc/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#3068 IOS-4407 Update middleware
  Libraryfile
Labels: Release

#3081 IOS-4415 Update app icon
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/1024x1024 (3).png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Contents.json
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Dark-Icon-Anytype-1024@3x.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Anytype-1024@3x-2.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Dark-1024x1024.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Tinted-1024x1024.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Tinted-Icon-Any-1024.png
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/60x60.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/Icon-Dark-60x60.pdf
Labels: Release

#3092 iOS-4428 Fix loc
  Makefile
  Modules/Loc/Sources/Loc/Generated/Strings.swift
Labels: Release

#3095 IOS-4415 Update app icon (again)
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Contents.json
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Dark-Icon-Anytype-1024@3x.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Anytype-1024@3x-2.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Anytype-1024@3x.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Tinted-Icon-Any-1024.png
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/Icon-Dark-60x60.pdf
Labels: 🧠 No brainer, Release

#3096 IOS-4436 Fix sentry error on home screen after primitives
  Anytype/Sources/ServiceLayer/Subscriptions/FavoriteSubscriptionService.swift
Labels: 🧠 No brainer, Release

#3109 IOS-4440 Update middleware
  Libraryfile
Labels: 🧠 No brainer, Release

#3114 iOS-4448 Update to middle v0.40.12
  Libraryfile
  Modules/Services/Sources/Generated/ObjectTypeUniqueKey+Bundled.swift
  Modules/Services/Sources/Models/ObjectTypeUniqueKey.swift
Labels: Release

#3117 Ios-4441 spacing between wallpaper and bin
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
Labels: Release

#3119 IOS-4442 Updated properties icon
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashMenuItemType.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSetting.swift
  Modules/Assets/Sources/Assets/Generated/ImageAssets.swift
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/ObjectSettings/Relations.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/ObjectSettings/Relations.imageset/Fields.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Properties.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Properties.imageset/Properties.svg
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Relations.imageset/Relations.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x40/Properties.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x40/Properties.imageset/Properties.svg
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x40/Relations.imageset/Relations.pdf
Labels: Release

#3120 IOS-4433 Fixed relation creation
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
Labels: 🐞 Bug, Release

#3123 IOS-4355 Relation Calendar View | Fix color
  Anytype/Sources/PresentationLayer/Common/SwiftUI/RelationDetailsViews/Date/RelationCalendarView.swift
Labels: 🧠 No brainer

#3124 Ios-4444 Show pre migration featured relations in case of conflict
  Anytype/Sources/Models/Documents/Document/BaseDocument.swift
  Anytype/Sources/Models/Documents/Document/BaseDocumentProtocol+Sync.swift
  Anytype/Sources/Models/Relations/RelationsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/SetContentViewDataBuilder.swift
Labels: Release

#3125 IOS-4386 Add object type featured relation movable
  Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift
Labels: Release

#3128 IOS-4444 Fix relationsDetails retrieval
  Anytype/Sources/Models/Documents/Document/BaseDocument+Extensions.swift
  Anytype/Sources/Models/Relations/ParsedRelations.swift
  Anytype/Sources/Models/Relations/RelationsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSettingsPrimitivesConflictManager.swift
Labels: 🐞 Bug, Release

#3126 IOS-4419 Block Link | Fix title
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/Link/BlockLinkCardView.swift
Labels: 🧠 No brainer

#3130 iOS-4415 Revert icon
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/1024x1024 (3).png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Contents.json
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Anytype-1024@3x.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Dark-1024x1024.png
  Anytype/Resources/SystemAssets.xcassets/AppIcon.appiconset/Icon-Tinted-1024x1024.png
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/60x60.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/AppIconsPreview/AppIcon.imageset/Icon-Dark-60x60.pdf
Labels: Release

#3129 Ios-4439 Added ability to drop into empty hidden section
  Anytype/Sources/Models/Relations/RelationsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift
Labels: 🐞 Bug, Release

#3132 IOS-4452 Remove simplified create button from type set
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
Labels: Release

#3131 IOS-4439 Fix local properties addition to the type
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsViewModel.swift
Labels: 🐞 Bug, Release

#3139 IOS-4453 Log screen type for type set
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: Release

#3147 IOS-4467 Supported object type change from relations menu
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorViewModel.swift
Labels: Release

#3154 iOS-4454 Remove unneeded print
  Modules/AnytypeCore/AnytypeCore/Utils/CoreEnvironment.swift
Labels: 🧠 No brainer

#3159 IOS-4483 Fix disappeared assets for markup menu
  Anytype/Sources/PresentationLayer/Common/UIKit/BottomSheets/TextStyleView/StyleView.swift
Labels: 🐞 Bug, Release

#3160 IOS-4482 bump patch version
  Anytype.xcodeproj/project.pbxproj
Labels: Release

#3163 iOS-4486 DEMO | 1920 image for fullscreen
  Anytype/Sources/PresentationLayer/Common/UIKit/ImageViewer/ImageViewer/Handlers/ImagePreviewMediaHandler.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: PR to branch

#3173 iOS-4493 File preview | ignore network error
  Anytype/Sources/PresentationLayer/Common/UIKit/ImageViewer/ImageViewer/Handlers/FilePreviewMediaHandler.swift
Labels: 🧠 No brainer

#3174 IOS-4494 Auth Service | Do not send to sentry accountStoreNotMigrated
  Modules/Services/Sources/Services/Auth/AuthMiddleService.swift
Labels: 🧠 No brainer

#3187 IOS-4503 Bump version
  Anytype.xcodeproj/project.pbxproj
Labels: Release

#3197 iOS-4500 Push alert - design fix
  Anytype/Sources/PresentationLayer/PushNotificationsAlert/PushNotificationsAlertView.swift
Labels: 🧠 No brainer, PR to branch

#3195 iOS-4500 Impl push notifications custom alert logic
  Anytype/Sources/ApplicationLayer/AppConfigurators/Configurators/FirebaseConfigurator.swift
  Anytype/Sources/ApplicationLayer/AppDelegate.swift
  Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/ChatCoordinator/ChatCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatModuleOutput.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
  Anytype/Sources/PresentationLayer/PushNotificationsAlert/PushNotificationsAlertView.swift
  Anytype/Sources/PresentationLayer/PushNotificationsAlert/PushNotificationsAlertViewModel.swift
  Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsAlertHandler/PushNotificationsAlertHandler.swift
  Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsPermissionService.swift/PushNotificationsPermissionService.swift
  Anytype/Sources/ServiceLayer/PushNotifications/PushNotificationsRegistrationService/PushNotificationsRegistrationService.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
Labels: PR to branch

#3200 IOS-4504 Space Loading indicator | remove hidden bottom panel
  Anytype/Sources/PresentationLayer/Flows/SpaceLoadingContainer/SpaceLoadingContainerView.swift
Labels: 🧠 No brainer

#3208 iOS-4410 Push notifications | Remove redundant toggle
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 No brainer, PR to branch

#3211 iOS-4542 Open exact chat by tap on push
  Anytype/Sources/ApplicationLayer/AppDelegate.swift
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Anytype/Sources/ServiceLayer/AppActions/AppAction.swift
  AnytypeNotificationServiceExtension/NotificationService.swift
  Modules/Services/Sources/Models/DecryptedPushKeys.swift
Labels: PR to branch

#3227 iOS-4561 Update last middle + handle spaceName and senderName
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/ServiceLayer/EncryptionKeyEventHandler/EncryptionKeyEventHandler.swift
  AnytypeNotificationServiceExtension/NotificationService.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Loc/Generated/Error+Localization.swift
  Modules/ProtobufMessages/Sources/Protocol/Commands/Anytype_Rpc.Workspace.Open.swift
  Modules/ProtobufMessages/Sources/Protocol/Events/Anytype_Event.Message.OneOf_Value.swift
  Modules/ProtobufMessages/Sources/Protocol/Events/Anytype_Event.Message.swift
  Modules/ProtobufMessages/Sources/Protocol/Events/Anytype_Event.PushEncryptionKey.Update.swift
  Modules/ProtobufMessages/Sources/Protocol/Events/Anytype_Event.PushEncryptionKey.swift
  Modules/Services/Sources/Models/DecryptedPushContent.swift
  Modules/Services/Sources/Services/DecryptionPushContentService/DecryptionPushContentService.swift
  Modules/Services/Sources/Services/EncryptionKeyService/EncryptionKeyService.swift
Labels: PR to branch

#3231 iOS-4569 Update middle
  Libraryfile
Labels: Release
