Repository anyproto/anytype-swift, pull requests merged in 2025-08, with the labels that each got.

#3716 IOS-4815 Fix publishing url
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/Model/Participant+Publishing.swift
Labels: Release

#3720 Ios-4947 space settings design review
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceProfile/SpaceProfileView.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsViewModel.swift
  Modules/Assets/Sources/Assets/Generated/ImageAssets.swift
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x32/copy link.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x32/copy link.imageset/copy link.svg
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x32/share link.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x32/share link.imageset/share link.svg
Labels: Release

#3722 IOS-4908 Publishing design review
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
  Modules/DesignKit/Sources/DesignKit/Fonts/Config/AnytypeFontConfig.swift
Labels: Release

#3738 IOS-4908 Web publishing | Design review
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/SpaceSettingsView.swift
Labels: Release

#3739 iOS-4989 Space Loading | Add icon animation
  Anytype/Sources/ApplicationLayer/Launch/LaunchCircle.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/PulseAnimation.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceLoadingContainer/SpaceLoadingContainerView.swift
Labels: Release

#3740 Ios-4992 remove large space before object header on scroll
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/NavigationBar/SyncStatus/EditorWebBannerItem.swift
Labels: 🐞 Bug, Release

#3745 IOS-4908 Web publishing | Fix design for small screens
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Labels: 🐞 Bug, 🧠 No brainer, Release

#3747 IOS-5002 Show qr code picker
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceTypePicker/SpaceTypePickerView.swift
Labels: Release

#3763 IOS-5003 Chat Widget toggles | split show and create
  Anytype/Sources/Models/AnytypeWigetId+Extensions.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/Helpers/SpaceHubSpacesStorage.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: Release

#3762 IOS-5017 Url encode publishing uri
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalViewModel.swift
Labels: Release

#3764 IOS-4908 Publishing design review
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/View/PublishingPreview.swift
Labels: Release

#3776 IOS-4908 Design fixes
  Anytype/Sources/PresentationLayer/Modules/PublishToWeb/PublishToWebInternalView.swift
Labels: 🧠 No brainer, Release

#3822 iOS-5064 New auth | Update custom alert view style
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Alerts/AlertView.swift
Labels: PR to branch

#3841 iOS-5087 New auth | Skip email step if needed (for local only)
  Anytype/Sources/PresentationLayer/AuthNew/Join/JoinView/JoinViewModel.swift
Labels: PR to branch
