Repository anyproto/anytype-swift, pull requests merged in 2025-03, with the labels that each got.

#2906 iOS-4126 Counters | open chat on first unread message (MVP)
  Anytype.xcodeproj/project.pbxproj
  Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Anytype/Sources/Models/Documents/Events/Model/EventBunchSubscribtion.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatUpdate.swift
  Modules/AsyncTools/Package.swift
  Modules/AsyncTools/Sources/AsyncTools/AnyAsyncSequence.swift
  Modules/AsyncTools/Sources/AsyncTools/AsyncToManyStream.swift
  Modules/AsyncTools/Sources/AsyncTools/ConvertDataStream.swift
  Modules/AsyncTools/Sources/AsyncTools/MergeFirstValue.swift
  Modules/AsyncTools/Sources/AsyncTools/TaskStream.swift
  Modules/AsyncTools/Tests/AsyncToolsTests/AsyncToolsTests.swift
  Modules/Services/Sources/Models/ChatModels.swift
Labels: PR to branch

#2916 IOS-4239 Primitives | Filter out description from relation list
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Labels: 🧠 No brainer

#2922 iOS-4144 Swift Concurrency | protobuf bump swift to 6
  Modules/ProtobufMessages/Package.swift
Labels: 🧠 No brainer

#2931 IOS-4165 Chat | Fix bookmark spacing
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/Attachments/MessageObjectBigBookmarkView.swift
Labels: 🧠 No brainer

#2930 IOS-4301 Lib Cache | use open date over create date for clean
  Scripts/middle-download.sh
Labels: 🧠 No brainer

#2935 IOS-4307 Primitives | Remove relation creation from featured section
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsRow.swift
  Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
Labels: 🧠 No brainer

#2947 iOS-4300 Chat | New Messages header
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessagesStorage.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMessageHeaderView.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Section/MessageSectionData.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Section/MessageSectionItem.swift
Labels: PR to branch

#2976 iOS-4335 Set guide use case for uxtype data
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateData.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Libraryfile
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/ProtobufMessages/Sources/Protocol/Commands/Anytype_Rpc.Object.ImportUseCase.swift
  Modules/Services/Sources/Models/UseCase.swift
Labels: PR to branch

#2972 iOS-4335 Demo | Set `none` use case for uxtype chat
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateData.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Libraryfile
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/ProtobufMessages/Sources/Protocol/Commands/Anytype_Rpc.Object.ImportUseCase.swift
  Modules/Services/Sources/Models/UseCase.swift
Labels: PR to branch

#2985 iOS-4338 Update auth key screen text
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#2908 IOS-4049 Support lastUsedDate sort for types in type picker
  Anytype/Sources/Models/Extensions/ObjectType+Extensions.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift
  Anytype/Sources/ServiceLayer/Object/TypeProvider/ObjectTypeProvider.swift
  Modules/AnytypeCore/AnytypeCore/Extensions/ProtobufExtensions.swift
  Modules/Services/Sources/Models/Details/BundledDetails.swift
  Modules/Services/Sources/Models/ObjectType.swift
Labels: Do not merge

#3009 IOS-4318 Design | Update arrow icons
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Down.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Down.imageset/Down.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Down.imageset/Variant=Down.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Left.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Left.imageset/Left.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Left.imageset/Variant=Left.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Right.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Right.imageset/Right.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Right.imageset/Variant=Right.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Up.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Up.imageset/Up.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/DesignSystem/x24/Arrow/Up.imageset/Variant=Up.pdf
Labels: 🧠 No brainer

#3010 IOS-4300 Chat | Fix loc
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#3011 IOS-4115 Chat | Dismiss keyboard by tap
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatView.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Labels: 🧠 No brainer

#3032 IOS-4044 Chat Input Attachments | Fix image size
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/InputPanel/Attachments/Local/ChatInputLocalImageView.swift
Labels: 🧠 No brainer
