Repository anyproto/anytype-swift, pull requests merged in 2025-01, with the labels that each got.

#2571 Ios-3636 Primitives | Supported relation deletion
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerAdditionalTests.swift
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveBetweenSectionTests.swift
  AnyTypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerMoveWithinSectionTests.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/DeleteIndicator.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/Model/TypeFieldsMoveHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
  AnytypeTests/Helpers/TypeFieldsMoveHandler/TypeFieldsMoveHandlerGeneralTests.swift
Labels: PR to branch

#2601 Ios-3905 Primitives | Conflict relations in object
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/MoreIndicator.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/List/ListSectionHeaderView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/List/SectionHeaderView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSection.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Entities/RelationsSectionBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/RelationsListRowView/RelationsListRowView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsViewModel.swift
Labels: PR to branch

#2602 IOS-3912 Primitives | Fix description behavior in lists
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
Labels: PR to branch

#2603 Ios-3908 Primitives | Check Edit details permission for types instead of layout
  Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Labels: PR to branch

#2609 IOS-3755 Renamed NewRelation -> RelationInfo
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoModuleInput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoModuleOutput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/Legacy/RelationsListView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/Legacy/RelationsListViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsViewModel.swift
Labels: 🧠 No brainer

#2612 IOS-3931 Rename relations -> fields
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/NewRelationView.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashAction.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Models/SlashMenuItemType.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/Model/ObjectSetting.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/ImagePreview/SetViewSettingsImagePreviewView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetRelationsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsList/SetViewSettings.swift
Labels: 🧠 No brainer, PR to branch

#2614 IOS-3755 Primitives | Add relation edit capabilities
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/Models/Relations/Entities/Relation.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/Subviews/NewRelationSectionView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationsListSearch/RelationsSearchCoordinatorViewModel.swift
  AnytypeTests/Markdown/Mocks/MockRelationsService.swift
  Modules/Services/Sources/Models/Relations/Models/RelationDetails.swift
  Modules/Services/Sources/Services/Relations/RelationsService.swift
  Modules/Services/Sources/Services/Relations/RelationsServiceProtocol.swift
Labels: PR to branch

#2632 IOS-3958 Design System | Update color name & add color
  Anytype/Generated/Assets.swift
  Anytype/Generated/Color+Assets.swift
  Anytype/Generated/Color+Info.swift
  Anytype/Generated/UIColor+Assets.swift
  Anytype/Resources/SystemColors.xcassets/DesignSystem/Control/transparentActive.colorset/Contents.json
  Anytype/Resources/SystemColors.xcassets/DesignSystem/Control/transparentInactive.colorset/Contents.json
  Anytype/Sources/PresentationLayer/Common/SwiftUI/BasicComponents/DynamicForeground.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ChatMessageHeaderView.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageReplyView.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/Message/MessageView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Submodule/WidgetsHeader/WidgetsHeaderView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Utils/EditorNavigationBarHelper/EditorNavigationBarHelper.swift
Labels: 🧠 No brainer

#2642 iOS-3973 Global search v2.0 | Add sorting / grouping when search request is empty
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x40/Sorts.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x40/Sorts.imageset/Sorts.pdf
  Anytype/Sources/PresentationLayer/Common/SwiftUI/ObjectsSortMenu/ObjectSort.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/ObjectsSortMenu/ObjectSortRelation.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/ObjectsSortMenu/ObjectsSortMenu.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchDataSection.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchState.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/AllContentStateStorage/AllContentStateStorageService.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Menu/AllContentSettingsMenu.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Menu/AllContentSortMenu.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Models/AllContentSort.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Models/AllContentState.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Subscription/AllContentSubscriptionService.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/Subscriptions/ObjectsListSubscriptionService.swift
  Anytype/Sources/ServiceLayer/Object/SearchWithMeta/SearchWithMetaService.swift
Labels: PR to branch

#2651 IOS-3985 Update middleware
  Anytype/Generated/Error+Localization.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Labels: Release

#2663 iOS-3992 Rename some GlobalSearch items to generic SearchWithMeta
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/GlobalSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/SearchWithMetaCell.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/SearchWithMetaModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/GlobalSearch/SearchWithMetaModelBuilder.swift
Labels: 🧠 No brainer

#2672 IOS-3897 Updated profile card design
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Edit.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x32/Edit.imageset/Edit.pdf
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Common/ImageCharIconView.swift
  Anytype/Sources/PresentationLayer/Modules/Profile/ProfileView.swift
Labels: Release

#2679 IOS-4018 Fix relation creation
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/RelationInfoView.swift
Labels: Release

#2680 iOS-4024 Update middleware
  Anytype/Generated/Error+Localization.swift
  Anytype/Sources/Models/Documents/Events/EventConverters/MiddlewareEventConverter.swift
  Anytype/Sources/Models/Relations/Entities/ObjectOrigin+Loc.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/commands+invocation.swift
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/events.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
Labels: Release

#2685 IOS-4030 Navigation | Fix sharing button enable logic
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeNavigationContainer/Panel/HomeBottomNavigationPanelViewModel.swift
Labels: Release

#2688 Ios-4001 Primitives | provide layout switch constraints
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
Labels: PR to branch

#2689 Ios-3970 Primitives | Provide limited object type for editing relations view @ignatovv
  Anytype/Sources/Models/Relations/Entities/Relation.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/RelationInfoData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/RelationInfoViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
Labels: PR to branch

#2696 iOS-4034 New navigation | fix restore logic
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/Utilities/UserDefaults/UserDefaultsStorage.swift
Labels: Release

#2705 iOS-4029 Add action To Bin in Simple Set
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift
Labels: PR to branch

#2703 iOS-4029 Add empty SimpleSet module
  Anytype/Sources/PresentationLayer/Flows/EditorFlow/EditorCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SimpleSetCoordinator/SimpleSetCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SimpleSetCoordinator/SimpleSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/Subscription/SimpleSetSubscriptionService.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData+Details.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/ScreenData.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
Labels: PR to branch

#2707 iOS-4029 Add pagination to Simple Set
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetState.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/Subscription/SimpleSetSubscriptionService.swift
Labels: PR to branch

#2712 IOS-4060 Any App | Fix marketing version
  Anytype.xcodeproj/project.pbxproj
Labels: 🧠 No brainer

#2717 Ios 4038 slash menu add relation
  Anytype/Sources/PresentationLayer/Flows/ChatCreateObject/ChatCreateObjectCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectTypeCoordinator/ObjectTypeCoordinatorModel.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/SpaceSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Date/DateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/FavoriteWidgetInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/WidgetObjectList/Favorites/WidgetObjectListFavoritesViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/WidgetType/Change/WidgetTypeChangeViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/InternalViewModels/RelationsSearchViewModel/RelationsInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Internal/WidgetSourceSearchChangeInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Settings/Coordinator/SettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleAssembly.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockContentView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Audio/AudioBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/BlockFileView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/File/BlockFileViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/File/Image/BlockImageViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/OpenFile/OpenFileBlockViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Layout/ObjectLayoutPickerViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectSettings/ObjectSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsViewModel.swift
  Anytype/Sources/ServiceLayer/ServicesDI.swift
Labels: PR to branch

#2716 Ios-4050 Primitives | First fixes after initial testing
  Anytype/Sources/PresentationLayer/Flows/ObjectTypeCoordinator/ObjectTypeCoordinatorModel.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/EditorScreenData.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: PR to branch

#2718 IOS-4047 Primitives | Fix type details update for pins
  Anytype/Sources/ServiceLayer/Block/Widget/BlockWidgetExpandedService.swift
  Anytype/Sources/ServiceLayer/Object/TypesService/TypesPinStorage.swift
Labels: PR to branch

#2719 IOS-4051 Primitives | Supported new navigation
  Anytype/Sources/PresentationLayer/Modules/ObjectType/ObjectTypeView.swift
Labels: PR to branch
