Repository anyproto/anytype-swift, pull requests merged in 2025-02, with the labels that each got.

#2721 iOS-4070 integrate v0393
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
Labels: Release

#2722 iOS-4069 Disable collaborate on spaces tip
  Anytype/Generated/ImageAssets.swift
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/Contents.json
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step1.imageset/1.png
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step1.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step2.imageset/2.png
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step2.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step3.imageset/3.png
  Anytype/Resources/Assets.xcassets/Tips/SpaceShareTip/step3.imageset/Contents.json
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareHandler.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareTip.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareTipView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareTip/SpaceShareTipViewModel.swift
  Modules/DeepLinks/Sources/DeepLinks/DeepLink.swift
  Modules/DeepLinks/Sources/DeepLinks/DeepLinkParser.swift
Labels: Release

#2725 iOS-4075 Replace ‘files’ with ‘attachments’
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: 🧠 No brainer

#2730 iOS-4088 integrate v0395
  Libraryfile
Labels: Release

#2735 IOS-4089 Primitives | Fix setOf relation handling
  Anytype/Sources/Models/Relations/ParsedRelations.swift
  Anytype/Sources/Models/Relations/RelationsBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Models/SetDocument.swift
Labels: PR to branch

#2742 Ios-3800 Primitives | Design review
  Anytype/Sources/PresentationLayer/Common/SwiftUI/List/SectionHeaderView.swift
  Anytype/Sources/PresentationLayer/Modules/ObjectType/Views/ObjectsList/ObjectTypeObjectsListView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypeFieldsView/TypeFieldsView.swift
Labels: PR to branch

#2750 iOS4028 Type Widget | Support create widget flag
  Libraryfile
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/Services/Sources/Services/Dataview/DataviewService.swift
  Modules/Services/Sources/Services/ObjectActions/ObjectActionsService.swift
  Modules/Services/Sources/Services/Templates/TemplatesService.swift
Labels: PR to branch

#2747 iOS-3934 Migration | Fix circular loader
  Anytype/Sources/PresentationLayer/Common/SwiftUI/CircularProgressBar/CircularProgressBar.swift
Labels: PR to branch

#2752 iOS-4043 Chat | fix open keyboard for attachments
  Anytype/Sources/PresentationLayer/Modules/Chat/ChatViewModel.swift
Labels: 🧠 No brainer

#2751 IOS-4028 Type widget | filter sources by created widgets
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/ObjectSearch/ObjectSearchViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetChangeSourceSearchView.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchView.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/ServiceLayer/Object/Search/SearchService.swift
  Anytype/Sources/ServiceLayer/Object/Search/SearchServiceProtocol.swift
Labels: PR to branch

#2771 iOS-4132 Demo | Disable set and collection hardcode widgets
  Anytype/Sources/Models/AnytypeWigetId+Extensions.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
Labels: PR to branch

#2773 iOS-4131 Demo | Update middle + support automatic widget for media
  Libraryfile
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/ProtobufMessages/Sources/Protocol/models.pb.swift
  Modules/Services/Sources/Generated/BundledRelationKey.swift
  Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
  Modules/Services/Sources/Services/FileService/FileService.swift
Labels: PR to branch

#2779 iOS-4149 Remove Create object option from Widget source
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Labels: PR to branch

#2780 iOS-4148 Add object type section in Widget source screen
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchViewModel.swift
Labels: PR to branch

#2783 iOS-4151 Space Creation | New space type picker
  Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Anytype/Generated/ImageAssets.swift
  Anytype/Generated/Strings.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Chat.imageset/Chat.pdf
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Chat.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Space.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Space.imageset/Space.pdf
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Stream.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/Channel/Stream.imageset/Stream.pdf
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateData.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateModuleOutput.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubOutput.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceTypePicker/SpaceTypePickerRow.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceTypePicker/SpaceTypePickerView.swift
  Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceViewMock.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomFields.swift
  Modules/Services/Sources/Models/Space/SpaceAliases.swift
Labels: PR to branch

#2785 iOS-4152 Space Creation | support different ux types
  Anytype/Sources/PresentationLayer/Flows/GalleryInstallation/GalleryInstallationCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Modules/Services/Sources/Services/Workspace/WorkspaceService.swift
Labels: PR to branch

#2786 IOS-4153 Space Hub | Show space ux type
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
  Anytype/Sources/PreviewMocks/Mocks/WorkspacesStorageMock.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceAccessType+Localize.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceUxType+Localize.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceViewMock.swift
Labels: PR to branch

#2788 Ios-4125 Primitives | Moved types library to settings
  Anytype/Generated/ImageAssets.swift
  Anytype/Generated/Strings.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Object Type.imageset/Contents.json
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/Object Type.imageset/Object Type.pdf
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/Support/PageNavigationHeader.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/SpaceSettings/NewSpaceSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/AllContent/Models/ObjectTypeSection.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchView.swift
  Anytype/Sources/PresentationLayer/ObjectTypeSearch/ObjectTypeSearchViewSettings.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsModuleOutput.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/Views/TypesLibrary/ObjectTypesLibraryView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/SettingsScreenData.swift
Labels: PR to branch

#2793 iOS-4163 AI summary for Set / Collection
  Anytype/Generated/ImageAssets.swift
  Anytype/Generated/Strings.swift
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/AI.imageset/AI.pdf
  Anytype/Resources/Assets.xcassets/DesignSystem/x24/AI.imageset/Contents.json
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/AITool/AIToolView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/AITool/AIToolViewModel.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: PR to branch

#2629 iOS-3934 Migration | Tech implementation and design
  Anytype/Generated/Error+Localization.swift
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorView.swift
  Anytype/Sources/ApplicationLayer/AppCoordinator/ApplicationCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginView.swift
  Anytype/Sources/PresentationLayer/Auth/LoginFlow/LoginViewModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/CircularProgressBar/CircularProgressBar.swift
  Anytype/Sources/PresentationLayer/Migration/MigrationView.swift
  Anytype/Sources/PresentationLayer/Migration/MigrationViewModel.swift
  Libraryfile
  Modules/ProtobufMessages/Sources/Generated/service+invocation.swift
  Modules/ProtobufMessages/Sources/Protocol/commands.pb.swift
  Modules/Services/Sources/Generated/BundledRelationKey+SystemKeys.swift
  Modules/Services/Sources/Generated/BundledRelationKey.swift
  Modules/Services/Sources/Generated/BundledRelationsValueProvider.swift
  Modules/Services/Sources/Services/Auth/Errors/SelectAccountError.swift
  Modules/Services/Sources/Services/Migration/AccountMigrationError.swift
  Modules/Services/Sources/Services/Migration/AccountMigrationService.swift
  Modules/Services/Sources/ServicesDI.swift
Labels: Do not merge

#2798 iOS-4111 Disable newSettings toggle for release
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: Release

#2801 IOS-4159 Chat | Fix spacing - last in section
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Labels: 🧠 No brainer

#2805 IOS-4157 Chat | Improve message in reply
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Labels: 🧠 No brainer

#2808 IOS-4159 Chat Message | Fix spacing (again)
  Anytype/Sources/PresentationLayer/Modules/Chat/Services/ChatMessageBuilder.swift
Labels: 🧠 No brainer

#2813 iOS-4174 Update migration subtitle
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
Labels: Release

#2818 IOS-4181 My spaces -> My channels
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubView.swift
Labels: 🧠 No brainer

#2822 IOS-4104 Updated untitled localization
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/Models/Extensions/String+Name.swift
  Anytype/Sources/PresentationLayer/ObjectCreationSettings/Views/Picker/TemplatePickerView.swift
  Anytype/Sources/PresentationLayer/Settings/Settings/Sections/SettingsTextField.swift
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/BlocksViews/Blocks/TableOfContents/TableOfContentsContentProvider.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetHeaderSettingsView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Models/DataviewView+View.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/CreateObject/CreateObjectView.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceViewMock.swift
Labels: 🧠 No brainer

#2826 IOS-4189 Enable toggles
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 No brainer, PR to branch

#2833 iOS-4161 Chat navigation | Support spaceUxType
  Anytype/Sources/PresentationLayer/SpaceSettings/SpaceSettings/NewSpaceSettingsViewModel.swift
  Anytype/Sources/ServiceLayer/SpaceStorage/Models/SpaceView.swift
  Libraryfile
Labels: PR to branch

#2830 iOS-4164 Fix gallery cover height
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Gallery/Common/GalleryWidgetRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Collection/Cell/SetGalleryViewCell.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Table/Row/SetContentViewItemConfiguration.swift
Labels: PR to branch

#2842 iOS-4163 Integrate AI summary methods on set / collections
  .github/workflows/branch_build.yaml
  .github/workflows/dev_build.yaml
  .github/workflows/release_build.yaml
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/AITool/AIToolViewModel.swift
  Anytype/Sources/ServiceLayer/AIConfigBuilder/AIConfigBuilder.swift
  Anytype/Supporting files/Info.plist
  Libraryfile
  Modules/Services/Sources/Models/AI/AIProviderConfig.swift
  Modules/Services/Sources/Services/AI/AIService.swift
  Modules/Services/Sources/ServicesDI.swift
  fastlane/FastfileDeploy
  fastlane/FastlaneBranchBuild
  fastlane/SetEnv
Labels: PR to branch

#2847 iOS-4186 Widgets | Add bin widget from mw
  Anytype/Sources/Analytics/Converters/ObjectType+Analytics.swift
  Anytype/Sources/Models/AnytypeWigetId+Extensions.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsDI.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetsView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/HomeWidgetState.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/Models/WidgetSource.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetActionsViewCommonMenuProvider.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetCommonActionsMenuView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/WidgetSourceSearchInteractor.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift
Labels: PR to branch

#2849 iOS-4211 Impl simple set gallery view for images (hardcode)
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/SpecificInternalModels/SetObjectWidgetInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/ImagesGalleryView.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetLayout.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetView.swift
  Anytype/Sources/PresentationLayer/Modules/SimpleSet/SimpleSetViewModel.swift
Labels: PR to branch

#2854 iOS-4227 Add opportunity to set space icon during space creation
  Anytype/Sources/PresentationLayer/Common/SwiftUI/DashboardWallpaper.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/LocalIconView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerViewModel.swift
  Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift
  Modules/Services/Sources/Models/Details/ObjectIcon.swift
Labels: PR to branch

#2853 iOS-4216 Create space | Remove description and unique name title
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Common/SwiftUI/DashboardWallpaper.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/LocalIconView.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/IconView/Specific/Object/SpaceIconView.swift
  Anytype/Sources/PresentationLayer/Flows/GalleryInstallation/GalleryInstallationCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateData.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerViewModel.swift
  Anytype/Sources/ServiceLayer/IconColorService/IconColorService.swift
  Modules/Services/Sources/Models/Details/ObjectIcon.swift
  Modules/Services/Sources/Services/Workspace/WorkspaceService.swift
Labels: PR to branch

#2862 iOS-4227 Add coordinator for SpaceCreateModule
  Anytype/Sources/PresentationLayer/Flows/SpaceHub/SpaceHubCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/Coordinator/SpaceCreateCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/Coordinator/SpaceCreateCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceCreate/SpaceCreateViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Icon/Local/LocalObjectIconPickerViewModel.swift
Labels: PR to branch

#2870 iOS-4185 Remove change source option from widgets
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/HomeWidgetsCoordinator/HomeWidgetsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Bin/BinWidgetView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/CommonWidgetModuleOutput.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetActionsViewCommonMenuProvider.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Common/WidgetActionsMenu/WidgetCommonActionsMenuView.swift
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Widgets/Container/WidgetContainerView.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetChangeSourceSearchView.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Internal/WidgetSourceSearchChangeInternalViewModel.swift
  Anytype/Sources/PresentationLayer/Search screen/WidgetSourceSearch/WidgetSourceSearchViewModel/Models/WidgetChangeSourceSearchModuleModel.swift
  Modules/Services/Sources/Services/BlockWidget/BlockWidgetService.swift
Labels: PR to branch

#2872 iOS-4238 Update share invite link style
  Anytype/Sources/PresentationLayer/Modules/Chat/Subviews/ConversationEmptyStateView/ConversationEmptyStateView.swift
Labels: PR to branch

#2881 iOS-4180 Design | Fix invite paddings
  Anytype/Sources/PresentationLayer/Modules/InviteLink/InviteLinkView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceShare/SpaceShareView.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceTypePicker/SpaceTypePickerRow.swift
Labels: PR to branch

#2880 iOS-4257 Update createTypeWidgetIfMissing param
  Anytype/Sources/PresentationLayer/Modules/ShareOptions/ShareOptionsInteractor.swift
  Anytype/Sources/ServiceLayer/Block/File/FileActionsService.swift
  Anytype/Sources/ServiceLayer/Block/File/FileActionsServiceProtocol.swift
  Anytype/Sources/ServiceLayer/ChatActionService/ChatActionService.swift
  Modules/Services/Sources/Services/FileService/FileService.swift
Labels: PR to branch

#2884 iOS-4242 Separate guest link for stream
  Anytype/Generated/Strings.swift
  Anytype/Resources/Strings/en.lproj/Localizable.strings
  Anytype/Sources/PresentationLayer/Modules/InviteLink/InviteLinkView.swift
  Anytype/Sources/PresentationLayer/Modules/InviteLink/InviteLinkViewModel.swift
  Anytype/Sources/ServiceLayer/ParticipantSpacesStorage/Model/SpacePermissions.swift
Labels: PR to branch
