Repository anyproto/anytype-swift, pull requests merged in 2025-05, with the labels that each got.

#3235 iOS-4575 Fix KingfisherError cancellation error
  Anytype/Sources/CoreLayer/NetwrokLayer/AnytypeImageDownloader.swift
Labels: Release

#3236 iOS-4574 Integrate v0.40.18-hotfix-2
  Libraryfile
Labels: Release

#3246 iOS-4568 Updated onboarding flow
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/Analytics/AnalyticsConstants.swift
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthView.swift
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/EmailCollectionView/EmailCollectionView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/EmailCollectionView/EmailCollectionViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowCoordinator.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowViewModel.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/KeyPhraseView/KeyPhraseView.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/Models/JoinFlowState.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/Models/JoinFlowStep.swift
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/SoulView/SoulView.swift
  Anytype/Sources/PresentationLayer/Auth/PhraseTextView/UIPhraseTextView.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
  Modules/Assets/Sources/Assets/Generated/ImageAssets.swift
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/communication.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/communication.imageset/communication.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/greetings.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/greetings.imageset/greetings.pdf
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/local-internet.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/Auth/local-internet.imageset/local-internet.pdf
  Modules/DesignKit/Sources/DesignKit/Fonts/Config/AnytypeFont.swift
  Modules/DesignKit/Sources/DesignKit/Fonts/Config/AnytypeFontConfig.swift
  Modules/Loc/Sources/Loc/Generated/Strings.swift
Labels: Release

#3258 iOS-4591 Remove some old toggles
  Anytype/Sources/PresentationLayer/Modules/HomeWidgets/Container/HomeWidgetSubmoduleView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/ObjectActions/ObjectActionsViewModel.swift
  Modules/AnytypeCore/AnytypeCore/Generated/FeatureFlags+Flags.swift
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: 🧠 No brainer

#3259 iOS-4592 Onboarding - top offset fix
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/JoinFlowView.swift
Labels: Release

#3260 iOS-4595 Integrate v0.40.21
  Libraryfile
Labels: Release

#3286 iOS-4610 Fix email param on onboarding
  Anytype.xcodeproj/project.pbxproj
  Anytype/Sources/PresentationLayer/Auth/JoinFlow/EmailCollectionView/EmailCollectionViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/EmailVerification/EmailVerificationViewModel.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetViewModel.swift
  Modules/Services/Sources/Services/Membership/MembershipService.swift
Labels: Release

#3299 Ios-4421 Renamed fields to properties
  AnyTypeTests/Helpers/TypePropertiesMoveHandler/TypePropertiesMoveHandlerAdditionalTests.swift
  AnyTypeTests/Helpers/TypePropertiesMoveHandler/TypePropertiesMoveHandlerGeneralTests.swift
  AnyTypeTests/Helpers/TypePropertiesMoveHandler/TypePropertiesMoveHandlerMoveBetweenSectionTests.swift
  AnyTypeTests/Helpers/TypePropertiesMoveHandler/TypePropertiesMoveHandlerMoveWithinSectionTests.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/EditorSetFlow/EditorSetCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Set/EditorSetModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/RelationsListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectPropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectPropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/Views/ObjectPropertiesBottomAlert.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/RelationDetails+Identifiable.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesDropDelegate.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesMoveHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesRowBuilder.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/EditorSetViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetFullHeader.swift
  Modules/Services/Sources/Models/Details/BundledRelationValueProvider+CustomProperties.swift
Labels: 🧠 No brainer

#3300 IOS-4616 Core | Fix test plan
  AnyTypeTests/AnytypeTests.xctestplan
Labels: 🧠 No brainer

#3320 IOS-4421 SetRelations -> SetProperties
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/Model/TypePropertiesRow.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/Coordinator/SetFiltersListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Filters/List/Coordinator/SetFiltersListCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/Coordinator/SetPropertiesCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/Coordinator/SetPropertiesCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/ImagePreview/SetViewSettingsImagePreviewView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetViewSettingsProperty.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SearchView/SetPropertiesDetailsLocalSearchView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/SetViewSettings/SetViewSettingsCoordinatorView/SetViewSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Coordinator/SetSortsListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Coordinator/SetSortsListCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Search/SetPropertiesDetailsLocalSearchInteractor.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/Sorts/Search/SetSortsSearchViewModel.swift
Labels: 🧠 No brainer

#3328 IOS-4474 Added log reorder space
  Anytype/Sources/Analytics/AnytypeAnalytics/AnytypeAnalytics+Events.swift
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubDropDelegate.swift
Labels: 🧠 No brainer

#3332 Ios-4479 Updated type icon
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/CustomIcons/Main/type.imageset/Contents.json
  Modules/Assets/Sources/Assets/Resources/Assets.xcassets/CustomIcons/Main/type.imageset/Type.svg
  Modules/Services/Sources/Models/Details/ObjectIconBuilder.swift
Labels: 🧠 No brainer

#3342 iOS-4656 Integrate v0.41.0-rc8 and enable push toggle
  Libraryfile
  Modules/AnytypeCore/AnytypeCore/Utils/FeatureFlags/FeatureDescription+Flags.swift
Labels: PR to branch

#3345 IOS-4658 Widgets | Reorder system widgets
  Modules/Services/Sources/Models/Details/Entities/AnytypeWidgetId.swift
Labels: 🧠 No brainer

#3347 IOS-4660 RelationInfo -> PropertyInfo
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoCoordinatorView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/View/PropertyInfoView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoModuleInput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoModuleOutput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/AccessoryView/SlashMenu/Handler/SlashMenuActionHandler.swift
  Anytype/Sources/PresentationLayer/TextEditor/Assembly/Page/EditorPageModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouter.swift
  Anytype/Sources/PresentationLayer/TextEditor/Routing/Editor/EditorRouterProtocol.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/SetPropertiesViewModel.swift
Labels: 🧠 No brainer

#3349 iOS-4665 Add token send on account create
  Anytype/Sources/PresentationLayer/Auth/Auth/AuthViewModel.swift
Labels: Release

#3351 IOS-4593 Membership | Supported legacy explorer tier
  Anytype/Sources/PresentationLayer/Modules/Membership/InitialScreen/MembershipModuleView.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTier+Upgrade.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/Models/MembershipTierExtensions.swift
  Anytype/Sources/PresentationLayer/Modules/Membership/TierSelection/OwnershipView/MembershipOwnerInfoSheetView.swift
  Modules/Services/Sources/Services/Membership/Model/MembershipTier.swift
Labels: Release

#3352 IOS-4662 Message preview | Add unread messages sort
  Anytype/Sources/PresentationLayer/Modules/SpaceHub/SpaceHubViewModel.swift
Labels: 🧠 No brainer

#3360 iOS-4671 Fix iOS 16-17 pushes
  Anytype.xcodeproj/project.pbxproj
  Libraryfile
Labels: Release

#3363 iOS-4678 Update middle
  Libraryfile
Labels: Release

#3366 IOS-4624 Chat | Change color
  Modules/Assets/Sources/Assets/Resources/SystemColors.xcassets/DesignSystem/Background/Chat/bubbleSomeones.colorset/Contents.json
Labels: 🧠 No brainer

#3376 IOS-4660 Refactor: Rename RelationFormatsList to PropertyFormatsList
  Anytype/Sources/Models/Relations/Entities/Relation.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoCoordinatorView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/Coordinator/PropertyInfoData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoModuleInput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoModuleOutput.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/CreateNewRelation/ViewModel/PropertyInfoViewModel.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/PropertyFormatsList/Entities/SupportedPropertyFormat.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/PropertyFormatsList/View/PropertyFormatListCell.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/PropertyFormatsList/View/PropertyFormatsListView.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/PropertyFormatsList/ViewModel/PropertyFormatsData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/PropertyFormatsList/ViewModel/PropertyFormatsListViewModel.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/RelationFormatsList/ViewModel/RelationFormatsData.swift
  Anytype/Sources/PresentationLayer/AddNewRelation flow/RelationFormatsList/ViewModel/RelationFormatsListViewModel.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/RelationSearchData.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Labels: 🧠 No brainer

#3378 Ios-4660 rename relation to property 6
  Anytype/Sources/Models/ObjectPermissions/ObjectPermissions.swift
  Anytype/Sources/PresentationLayer/Common/SwiftUI/Search/Common/Model/PropertySearchData.swift
  Anytype/Sources/PresentationLayer/Flows/EditorPageFlow/EditorPageCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorView.swift
  Anytype/Sources/PresentationLayer/Flows/ObjectSettingsFlow/ObjectSettingsCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/PropertiesListCoordinatorView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/PropertiesListCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Coordinator/PropertiesListModuleOutput.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/PropertiesListRowView/PropertiesListRowView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/PropertiesListRowView/Subviews/PropertyValuePlaceholderView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectPropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/ObjectFieldsView/ObjectPropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesView.swift
  Anytype/Sources/PresentationLayer/TextEditor/EditorPage/Views/Settings/Relations/Views/TypePropertiesView/TypePropertiesViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/Coordinator/SetPropertiesCoordinatorViewModel.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/PropertiesSearchData.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationView.swift
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Popups/RelationsSettings/RelationCreation/RelationCreationViewModel.swift
Labels: 🧠 No brainer

#3383 IOS-4681 Fixed singular name in minimized header
  Anytype/Sources/PresentationLayer/TextEditor/Set/Views/Header/SetMinimizedHeader.swift
Labels: 🧠 No brainer

#3396 IOS-3232 Chat | Change Color
  Modules/Assets/Sources/Assets/Resources/SystemColors.xcassets/DesignSystem/Background/Chat/bubbleSomeones.colorset/Contents.json
  Modules/Assets/Sources/Assets/Resources/SystemColors.xcassets/DesignSystem/Background/Chat/replySomeones.colorset/Contents.json
Labels: 🧠 No brainer
